### PR TITLE
feat: Ignore paths feast apply

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
# What this PR does / why we need it:

Ignores these files automatically from `feast apply`:

```
[
    ".git",
    ".feastignore",
    ".venv",
    ".pytest_cache",
    "__pycache__",
    ".ipynb_checkpoints",
]
```

# Which issue(s) this PR fixes:

https://github.com/feast-dev/feast/issues/3474

# Fixes

### CODE REVIEW

**Review by tokoko — APPROVED** [review]
lgtm

**Comment by franciscojavierarceo** [comment]
@HaoXuAI can you stamp?

**Comment by franciscojavierarceo** [comment]
@tokoko why didn't your approval work? 🤔

**Comment by tokoko** [comment]
I think because I don't have write access on the repo.

**Comment by franciscojavierarceo** [comment]
can you try /approve ?

**Review by tokoko — APPROVED** [review]
approved

**Comment by franciscojavierarceo** [comment]
I meant `/approve` 😅

**Comment by tokoko** [comment]
@franciscojavierarceo right, sorry about that 😄 I don't think prow is enabled though. Not sure how one would do that, I have never used it before.

**Review by HaoXuAI — APPROVED** [review]

**Pull request merged**
