### PR TITLE
Fixes python 3.6 issue

### LINKED ISSUE #1502: Python 3.6 Local Mode breaks due to usage of pathlib.Path and sqlite3
## Expected Behavior 

Python 3.6 in local mode works when following the quickstart 

## Current Behavior

Unable to follow quickstart due to the error as shown below

## Steps to reproduce

1. Create a Python 3.6 environment. E.g. `conda create --name=feast36 python=3.6`
2. Install feast and other deps `pip install feast`
3. Follow the quickstart

When running the quick start it will fail with the following msg.

```
(feast36) ➜  temp_feat$ feast init feat1

Creating a new Feast repository in /home/user/Documents/temp_feat/feat1.

(feast36) ➜  temp_feat$ cd feat1
(feast36) ➜  feat1$ feast apply
Registered entity driver_id
Registered feature view driver_hourly_stats
Deploying infrastructure for driver_hourly_stats
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/feast36/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/feast/cli.py", line 160, in apply_total_command
    apply_total(repo_config, Path.cwd())
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/feast/repo_operations.py", line 148, in apply_total
    partial=False,
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/feast/infra/local.py", line 55, in update_infra
    conn = self._get_conn()
  File "/home/user/anaconda3/envs/feast36/lib/python3.6/site-packages/feast/infra/local.py", line 45, in _get_conn
    self._db_path, detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES
TypeError: argument 1 must be str, not PosixPath
```

### Specifications

- Version: 3.6
- Platform: Ubuntu 20.04, also tested on Ubuntu 18.05
- Subsystem:

## Possible Solution

The sqlite3 issue is resolved in Python 3.7 as shown here:
https://bugs.python.org/issue33496

A solution could be to add `self._db_path = str(self._db_path)` or similar in the `infra/local.py` file

I couldn't find a similar issue - in the case its resolved in an upstream commit...

### PR DESCRIPTION
**Pull request by chappers**
**What this PR does / why we need it**:

This PR address errors which working in Python 3.6 local mode
I have tested briefly on Python 3.8 (Ubuntu 20.04)

**Which issue(s) this PR fixes**:

Fixes #1502
I have tested against Python 3.8 on Ubuntu as well. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE 
```

### CODE REVIEW

**Comment by tsotnet** [comment]
@chappers Thank you for submitting a PR. The issue here is that we do not support Python 3.6. You need to be on Python 3.7+ to use Feast. Unfortunately our [setup.py](https://github.com/feast-dev/feast/blob/master/sdk/python/setup.py) does not reflect that, but we'll update it.

**Comment by Joostrothweiler** [comment]
@tsotnet could you maybe elaborate on the rationale behind the decision not to support Python 3.6?

**Pull request closed without merging**
