### PR TITLE
Make `feast registry-dump` print the whole registry as one json

### PR DESCRIPTION
**Pull request by nossrannug**
**What this PR does / why we need it**:
When running `feast registry-dump`, the whole registry is printed as one json.

I intentionally kept all the logic in repo_operations.py instead of adding a method to the Registry class since this is for debugging only.

**Changes**

The current implementation will print the json representation of each entity and feature view but none of the other objects such as feature services and on demand feature views. It is also not obvious which type each json represents.
```json
{
  "spec": {
    "name": "driver_id",
    "valueType": "INT64",
    "description": "driver id",
    "joinKey": "driver_id"
  },
  "meta": {}
}
{
  "spec": {
    "name": "driver_hourly_stats",
    "entities": [
      "driver_id"
    ],
    "features": [
      {
        "name": "conv_rate",
        "valueType": "FLOAT"
      },
      {
        "name": "acc_rate",
        "valueType": "FLOAT"
      },
      {
        "name": "avg_daily_trips",
        "valueType": "INT64"
      }
    ],
    "ttl": "86400s",
    "batchSource": {
      "type": "BATCH_FILE",
      "eventTimestampColumn": "event_timestamp",
      "createdTimestampColumn": "created",
      "fileOptions": {
        "fileUrl": "/content/feature_repo/data/driver_stats.parquet"
      },
      "dataSourceClassType": "feast.infra.offline_stores.file_source.FileSource"
    },
    "online": true
  },
  "meta": {}
}
```
The change in this PR would print one json object containing a list of all objects of the registry.
```json
Warning: The registry-dump command is for debugging only and may contain breaking changes in the future. No guarantees are made on this interface.
{
  "entities": [
    {
      "spec": {
        "name": "driver_id",
        "valueType": "INT64",
        "description": "driver id",
        "joinKey": "driver_id"
      },
      "meta": {}
    }
  ],
  "featureViews": [
    {
      "spec": {
        "name": "driver_hourly_stats",
        "entities": [
          "driver_id"
        ],
        "features": [
          {
            "name": "conv_rate",
            "valueType": "FLOAT"
          },
          {
            "name": "acc_rate",
            "valueType": "FLOAT"
          },
          {
            "name": "avg_daily_trips",
            "valueType": "INT64"
          }
        ],
        "ttl": "86400s",
        "batchSource": {
          "type": "BATCH_FILE",
          "eventTimestampColumn": "event_timestamp",
          "createdTimestampColumn": "created",
          "fileOptions": {
            "fileUrl": "/content/feature_repo/data/driver_stats.parquet"
          },
          "dataSourceClassType": "feast.infra.offline_stores.file_source.FileSource"
        },
        "online": true
      },
      "meta": {}
    }
  ],
  "featureServices": [
    {
      "spec": {
        "name": "driver_activity",
        "features": [
          {
            "featureViewName": "driver_hourly_stats",
            "featureColumns": [
              {
                "name": "avg_daily_trips",
                "valueType": "INT64"
              }
            ]
          },
          {
            "featureViewName": "driver_hourly_stats",
            "featureColumns": [
              {
                "name": "conv_rate",
                "valueType": "FLOAT"
              }
            ]
          }
        ]
      },
      "meta": {}
    }
  ]
}

```
The json object will contain entities, featureViews, featureTables, featureServices, onDemandFeatureViews, and requestFeatureViews.

```release-note
NONE
```

### CODE REVIEW

**Comment by woop** [comment]
@nossrannug can you please describe the change (before / after)?

**Comment by nossrannug** [comment]
Hey @woop, I've updated the top comment to include the before and after json blobs

**Comment by woop** [comment]
Looks good to me. I think we should also print a warning that the `registry-dump` command may contain breaking changes in the future and that no guarantees are made on this interface.

**Comment by nossrannug** [comment]
Added this message to the output:
**Warning: The registry-dump command is for debugging only and may contain breaking changes in the future. No guarantees are made on this interface.**

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
