### PR TITLE
docs: Fix the documentation to run the tutorial Validating historical features with Great Expectations

### PR DESCRIPTION
**Pull request by diefergil**
**What this PR does / why we need it**:

The great expectactions tutorial is not working properly, I managed to run it with some small changes in the code and I thought it would be good to update it.

**Which issue(s) this PR fixes**:

The complete great expectations tutorial can now be run by copying and pasting the code from the documentation.

Fixes #

### CODE REVIEW

**Comment by felixwang9817** [comment]
@diefergil thanks for the PR! you'll have to [sign your commit](https://docs.feast.dev/project/development-guide#signing-off-commits) in order for the DCO check to pass

**Comment by diefergil** [comment]
> @diefergil thanks for the PR! you'll have to [sign your commit](https://docs.feast.dev/project/development-guide#signing-off-commits) in order for the DCO check to pass

Done!

**Comment by felixwang9817** [comment]
@diefergil actually I don't think the commit was actually signed off? can you try again?

**Comment by felixwang9817** [comment]
@diefergil are you sure you're following the instructions correctly? I'm still not seeing the signature on your commit

**Comment by diefergil** [comment]
Hello again @felixwang9817 . You were right, I thought the github verified was enough. I have now configured gpg and I think it should be enough. If not, send me a guide on how to configure it properly. Thanks!

**Comment by felixwang9817** [comment]
@diefergil it's still not working. you can find the instructions [here](https://docs.feast.dev/project/development-guide#signing-off-commits). you'll know that it's working when the DCO check is passing.

**Comment by diefergil** [comment]
Now is working! Thanks for your help @felixwang9817!

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
