### PR TITLE
feat: Faiss and In memory store

### PR DESCRIPTION
**Pull request by HaoXuAI**
# What this PR does / why we need it:

# Which issue(s) this PR fixes:

# Misc

### CODE REVIEW

**Comment by HaoXuAI** [comment]
@franciscojavierarceo @tokoko an tentative implementation for faiss + inmemory db for vector store

**Review by franciscojavierarceo — APPROVED** [review]
lgtm

**Comment by dmartinol** [comment]
Hey, I just integrated this change to raise a new PR and the linter failed:
```
feast/infra/online_stores/contrib/faiss_online_store.py:173: error: Return type "list[tuple[datetime | None, Value | None, Value | None, Value | None]]" of "retrieve_online_documents" incompatible with return type "list[tuple[datetime | None, EntityKey | None, Value | None, Value | None, Value | None]]" in supertype "OnlineStore"  [override]
```
Its return type:
```py
    ) -> List[
        Tuple[
            Optional[datetime],
            Optional[Value],
            Optional[Value],
            Optional[Value],
        ]
    ]:
```
does not match the supertype signature:
```py
    ) -> List[
        Tuple[
            Optional[datetime],
            Optional[EntityKeyProto],
            Optional[ValueProto],
            Optional[ValueProto],
            Optional[ValueProto],
        ]
    ]:
```
Can you pls take a look?

**Comment by franciscojavierarceo** [comment]
Just to close this thread, I fixed this.

**Pull request merged**
