### PR TITLE
Compute and write metrics for rows prior to store writes

### PR DESCRIPTION
**Pull request by zhilingc**
**What this PR does / why we need it**:

In PR #568, ingestion metrics were shifted to be computed and written post-store-writes, in order to accurately reflect the values that are actually available to users. 

However, for certain stores (like BQ), successfully written rows cannot be retrieved post-write, and as a result feature row metrics are not produced for ingestion jobs writing to such stores. This PR re-introduces inflight feature row metrics as an alternative source of monitoring.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Adds the tag "metrics_namespace" to the following metrics:
- feature_row_lag_ms_*
- feature_value_lag_ms_*
- feature_row_ingested_count
- feature_value_missing_count
- feature_value_*

The tag can contain either of:
- `Inflight` 
- `WriteToStoreSuccess`
```

### CODE REVIEW

**Comment by Yanson** [comment]
Does this fix #747?

**Comment by zhilingc** [comment]
> Does this fix #747?

Sort of. It provides an alternative means to monitor elements being ingested when the sink is BigQuery.

**Comment by woop** [comment]
@zhilingc can we add this change in metrics to our documentation please?

**Pull request merged**
