### PR TITLE
Improve online deserialization latency

### PR DESCRIPTION
**Pull request by judahrand**
Signed-off-by: Judah Rand <17158624+judahrand@users.noreply.github.com>

**What this PR does / why we need it**:
For `_LIST` type features this implementation is up to 7x faster in my testing. 

For serializing and deserializing 10k rows of 3 columns `DOUBLE`, 3 columns `FLOAT_LIST`.

Old implementation:
image

New implementation:
image

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by judahrand** [comment]
@tsotnet Relevant for your benchmarking perhaps?

**Comment by achals** [comment]
This is great and much cleaner to read @judahrand - I'm curious where the speed up is coming from, is it just because we're avoiding the excess branching and if statements?

**Comment by judahrand** [comment]
> This is great and much cleaner to read @judahrand - I'm curious where the speed up is coming from, is it just because we're avoiding the excess branching and if statements?

I think it is the branching and ifs but also for list types the old implementation was looping over each element of the list and type casting it. This implementation avoids the need for that by not using `MessageToDict`. 

From what I can tell `MessageToDict` does some very odd things to types. Really it should probably be called `MessageToJSONDict`! Accessing the elements directly avoids the weirdness with types.

**Comment by judahrand** [comment]
I'd also add that this is relying much more on letting Protobuf sort out the conversions which might mean more of this is being done in C++ extensions?

**Comment by judahrand** [comment]
image

This is an interesting comparison between `master` and these changes for both with and without the C++ extensions.

**Comment by judahrand** [comment]
Looks like most platform's wheels from `pip` do use the C++ extensions by default which is a relief!

**Review by achals — APPROVED** [review]
/lgtm

**Comment by judahrand** [comment]
@achals Interestingly, there is the possibility of getting another small performance benefit by doing what is documented here: https://m.atthew.uk/posts/post.html

This is probably not worth the deploy nightmare, however.

**Comment by achals** [comment]
> @achals Interestingly, there is the possibility of getting another small performance benefit by doing what is documented here: https://m.atthew.uk/posts/post.html
> 
> 
> 
> This is probably not worth the deploy nightmare, however.

Thanks for the detailed info! Yeah I'm inclined to opt for simplicity over speed in this particular case. I'm sure there's other avenues to speed things up that won't complicate our packaging and deploy story.

**Pull request merged**
