### PR TITLE
Change Environment timestamps to be in UTC

### PR DESCRIPTION
**Pull request by felixwang9817**
Signed-off-by: Felix Wang <wangfelix98@gmail.com>

**What this PR does / why we need it**: Tests have been failing in PT due to timezone issues. This PR fixes those issues. 

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Review by achals — APPROVED** [review]
/lgtm

**Comment by adchia** [comment]
force merged since over two runs of the integration tests, different python versions flaked out each time (but all tests pass at least once over the two runs)

**Pull request merged**
