### PR TITLE
v0.5 backport: Restore SDK and Ingestion compatibility with Java 8 runtimes

### PR DESCRIPTION
**Pull request by ches**
**What this PR does / why we need it**:

Backports #722 to v0.5.

**Does this PR introduce a user-facing change?**:

```release-note
- Restores Feast Ingestion compatibility with Java 8 runtimes
- Restores Feast Java SDK compatibility with Java 8 runtimes
```

### CODE REVIEW

**Comment by ches** [comment]
Hmm probably we also need to backport #725, and perhaps #728.

**Comment by ches** [comment]
/retest

Maven Central connection blip it seems

**Comment by woop** [comment]
Those tests dont add any value to you though, I think. They are testing the current master branch. I've removed them from all non-master branches and all PRs. So they only trigger on a push to master and we can track them through the front page badge.

**Comment by ches** [comment]
> Wait a minute, they shouldn't have run on a PR in the first place. Strange.

I'd guess it's that b8456c1bdc1a4 isn't on `v0.5-branch`—my interpretation of [this] is that a pull request event is probably associated with the target branch as its Git ref, so the workflow configurations from the branch head will apply.

[this]: https://help.github.com/en/actions/reference/events-that-trigger-workflows#about-workflow-events

**Pull request merged**
