### PR TITLE
Respect specified ValueTypes for features during materialization

### LINKED ISSUE #1904: Float features are materialized into online stores as doubles
## Expected Behavior
For features defined as floats, online retrieval should NOT return double type.
## Current Behavior
Float features are materialized into online stores as double type.
## Steps to reproduce
Add the following assertion inside the `_assert_online_features()` function in `test_e2e_local.py`:
```python
assert response.field_values[0].fields[f"driver_hourly_stats__conv_rate"].float_val > 0
```
### Specifications

- Version: 0.13.0
- Platform: all
- Subsystem: Python SDK

## Possible Solution
In the function `python_value_to_proto_value()` of `type_map.py`, 
`value_type` perhaps should be set to `feature_type` if `feature_type` is not `None`:
```python
def python_value_to_proto_value(
    value: Any, feature_type: ValueType = None
) -> ProtoValue:
    value_type = (
        feature_type
        if feature_type is not None
        else python_type_to_feast_value_type("", value)
    )
    return _python_value_to_proto_value(value_type, value)
```

### PR DESCRIPTION
**Pull request by Agent007**
**What this PR does / why we need it**:
Float features are erroneously materialized to online stores as doubles. This bug could drastically affect the memory and  storage usage of online stores.

**Which issue(s) this PR fixes**:

Fixes #1904

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Agent007** [comment]
@judahrand , you may be interested in this pull request since you've been working on cleaning up type conversions.

**Comment by achals** [comment]
@Agent007 I've updated this PR with what I think is a more general fix. Thanks for your contribution! If it looks good after tests, i'll merge it in today.

**Comment by Agent007** [comment]
@achals Thanks!

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
