### PR TITLE
[WIP] Adding capabilities to specify schema for RedshiftSource

### LINKED ISSUE #1767: Add schema parameter to RedshiftSource to distinguish between database schemas
**Is your feature request related to a problem? Please describe.**
No possible way to specify schema via `table` parameter.
When you add schema parameter to table name e.g `schema_sample.feature_table` it throws exception when applying with message:
```
    raise DataSourceNotFoundException(self.table)
feast.errors.DataSourceNotFoundException: Unable to find table at 'schema_sample.feature_table'. Please check that table exists.
```

**Describe the solution you'd like**
Add optional `schema` parameter to uniquely identify which schema to use to reference source table.

**Describe alternatives you've considered**
`query` parameter works just fine

### PR DESCRIPTION
**Pull request by blvp**
**What this PR does / why we need it**:
This feature is required to eliminate undefined behaviour where users can specify a table which represented in multiple schemas.
**Which issue(s) this PR fixes**:

Fixes #1767 

**Does this PR introduce a user-facing change?**:

```release-note
RedshiftSource optional `schema` parameter support.
```

### CODE REVIEW

**Comment by blvp** [comment]
Created this Draft PR to start triggering integration tests. Going to also provide additional unit tests and integration tests with that edge case.

**Comment by woop** [comment]
This is great @blvp!

**Comment by felixwang9817** [comment]
Hey @blvp, just wanted to let you know that we recently added support for schemas in Redshift in #1847. If that looks alright to you, we can probably close out this PR.

**Comment by blvp** [comment]
Yeah makes sense. Original issue was fixed already.

**Pull request closed without merging**
