### PR TITLE
feat: Allow to pass secrets and environment variables to transformation service

### LINKED ISSUE #2631: Allow to pass secrets to transformation service chart
There is no way to use google cloud storage registry for transformation service as it requires some configurations like setting GOOGLE_CLOUD_PROJECT and access to the credentials.

**Describe the solution you'd like**
Allow to pass secrets and environment variables to the chart, same way it's possible for the feature-server chart.

**Describe alternatives you've considered**
Modify the chart and create a PR.

### PR DESCRIPTION
**Pull request by hermesdt**
Signed-off-by: Alvaro Duran Tovar <hermesdt@gmail.com>

**What this PR does / why we need it**:

Allow to pass secrets and environment variables to transformation service. Without this I can't use a GCS registry.

**Which issue(s) this PR fixes**:

Fixes #2631

### CODE REVIEW

**Review by pyalex — APPROVED** [review]

**Comment by pyalex** [comment]
@hermesdt can you please rebase your branch? It seems that there was an issue in master branch.

**Comment by hermesdt** [comment]
done @pyalex

**Review by achals — APPROVED** [review]

**Pull request merged**
