### PR TITLE
fix: Update sql.py

### PR DESCRIPTION
**Pull request by hao-affirm**
Signed-off-by: Hao Xu <hao.xu@affirm.com>
**What this PR does / why we need it**:
Fix a bug that `name = name or obj.name if hasattr(obj, "name") else None` has wrong order sequence.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by achals — APPROVED** [review]
Could you add a test for this fix?

**Comment by felixwang9817** [comment]
@hao-affirm you'll also need to [sign](https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md#signing-off-commits) your commit!

**Comment by hao-affirm** [comment]
@achals @felixwang9817 thanks. added test and signoff

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
