### PR TITLE
refactor: Refactor universal test data to have more well defined types

### PR DESCRIPTION
**Pull request by adchia**
**What this PR does / why we need it**:
Before, the test data and test objects used for the universal test suite tended to be a Dict[str, Any] with hardcoded keys. This converts those into data classes which allows for much better IDE integrations.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by felixwang9817** [comment]
btw @adchia looks like unit tests are failing here with `AttributeError: module 'functools' has no attribute 'cached_property'`; do you want to rebase on master and force push?

**Comment by adchia** [comment]
> btw @adchia looks like unit tests are failing here with `AttributeError: module 'functools' has no attribute 'cached_property'`; do you want to rebase on master and force push?

done!

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
