### PR TITLE
Optimize memory usage during materialization

### PR DESCRIPTION
**Pull request by judahrand**
**What this PR does / why we need it**:
I have run memory usage into issues on initial materialization of a large FeatureView with approaching 10 million rows and 30 columns. Acquiring the Arrow table succeeds but the conversion to Protobuf seems to require duplicating the whole dataset in memory which is not practical.

This initial improvement batches the table returned by `to_arrow` into RecordBatches which improves the situation. Looking forward I think that there should be the option (or requirement?) for RetrievalJobs to yield these RecordBatches directly to further reduce memory requirements.

This PR improves the situation from #2071 but I do not believe is enough to close it.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by judahrand** [comment]
Failures don't look related to PR

**Comment by adchia** [comment]
FYI @tsotnet looks like an issue with feature server docker images

**Pull request merged**
