### PR TITLE
fix: Update some fields optional in UI parser

### PR DESCRIPTION
**Pull request by mickey-liu**
**What this PR does / why we need it**:
The UI parser expects some fields to be mandatory even though the feast source api's do not, this PR makes the following fields optional:

- featureViews.meta.lastUpdatedTimestamp
- featureViews.meta.createdTimestamp
- featureViews.spec.batchSource.name
- entities.meta.createdTimestamp
- entities.meta.lastUpdatedTimestamp

Screenshots for how the UI looks when the above fields are missing vs when present

Screen Shot 2022-03-04 at 3 05 56 PM
Screen Shot 2022-03-04 at 3 05 50 PM
Screen Shot 2022-03-04 at 3 05 40 PM
Screen Shot 2022-03-04 at 3 05 32 PM

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by adchia** [comment]
mind signing your commit?

**Comment by mickey-liu** [comment]
I signed off my latest commit, is that sufficient or do I need to do something else?

**Comment by adchia** [comment]
all your commits in this need to be signed. you could also squash it all and then sign that?

**Comment by mickey-liu** [comment]
> all your commits in this need to be signed. you could also squash it all and then sign that?

Done

**Pull request closed without merging**
