### PR TITLE
fix: Feature logging to Redshift is broken

### PR DESCRIPTION
**Pull request by pyalex**
Signed-off-by: Oleksii Moskalenko <moskalenko.alexey@gmail.com>

**What this PR does / why we need it**:

Redshift requires the order of fields in parquet file (produced in Go) to exactly match schema (generated from feature service in Python). Even in field ordering. This PR fixes field ordering in schema generated in Python.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by felixwang9817 — COMMENTED** [review]
nit: maybe leave a comment explaining why this specific ordering is necessary and should be preserved?

also why wasn't this caught by a test?

**Comment by pyalex** [comment]
@felixwang9817 that's because we don't have a test for this due to our current environments setup (something that I fixing in different PR #2648 )

**Comment by felixwang9817** [comment]
@pyalex got it, do you mind adding the comment?

**Comment by pyalex** [comment]
@felixwang9817 Added a comment.

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Review by achals — APPROVED** [review]
/lgtm

**Review by achals — APPROVED** [review]
/lgtm

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
