### PR TITLE
Move java components to feast-java repo

### PR DESCRIPTION
**Pull request by jklegar**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Java components moved into a separate repository `feast-java`
```

### CODE REVIEW

**Comment by woop** [comment]
@jklegar you can remove m2 caching here https://github.com/feast-dev/feast/blob/e3e538fabb3638176ade34ffb769868fe947309e/.github/workflows/complete.yml

**Comment by woop** [comment]
And here https://github.com/feast-dev/feast/blob/e3e538fabb3638176ade34ffb769868fe947309e/.github/workflows/master_only.yml

**Comment by woop** [comment]
There are still some core/serving parts in the makefile https://github.com/feast-dev/feast/blob/e3e538fabb3638176ade34ffb769868fe947309e/Makefile#L89

**Comment by woop** [comment]
Is the CI dockerfile still used? Do we need the maven related steps?

**Comment by woop** [comment]
I think https://github.com/feast-dev/feast/blob/e3e538fabb3638176ade34ffb769868fe947309e/.scalafmt.conf can be removed as well.

**Comment by jklegar** [comment]
> Is the CI dockerfile still used? Do we need the maven related steps?

it's used in feast-spark, so we may want to transfer it to there

**Review by woop — APPROVED** [review]

**Pull request merged**
