### PR TITLE
Refresh Auth0 token

### PR DESCRIPTION
**Pull request by AnujaVane**
**What this PR does / why we need it**: Refreshes the OAuth token 500 seconds before it expires

**Does this PR introduce a user-facing change?**: NONE
<!--
If no, just write "NONE" in the release-note block below.
If yes, a release note is required:
Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the string "action required".

For more information about release notes, see kubernetes' guide here:
http://git.k8s.io/community/contributors/guide/release-notes.md

### CODE REVIEW

**Comment by woop** [comment]
Hey @AnujaVane. Are you running Feast 0.9? I think we should be making this change to the 0.9 branch. The code in question is scheduled for deletion.

**Comment by AnujaVane** [comment]
Hey @woop Just wondering, do you mean that the auth code is being deleted in the upcoming version? Can you give me more context on that? Or direct me to some documentation that does the same? Thanks!!

**Comment by woop** [comment]
> Hey @woop Just wondering, do you mean that the auth code is being deleted in the upcoming version? Can you give me more context on that? Or direct me to some documentation that does the same? Thanks!!

We are using the `FeatureStore` class going forward, and not the `Client` class any more.

**Comment by AnujaVane** [comment]
Hey @woop Thanks for the explanation, I'll create this MR into the v0.9 branch shortly.

**Pull request closed without merging**
