### PR TITLE
chore: Bump great expectation version

### LINKED ISSUE #3500: Greate Expectations version a bit outdated
## Expected Behavior 
GX version works well with >=0.15.41

## Current Behavior
It got pinned between 0.14 and 0.15

### Specifications

- Version: 0.29.0

## Possible Solution
Bump GX version

### PR DESCRIPTION
**Pull request by sudohainguyen**
**What this PR does / why we need it**: bump great expectation dependencies

**Which issue(s) this PR fixes**: 

Fixes #3500

### CODE REVIEW

**Comment by sudohainguyen** [comment]
unit test failed due to 
`"pkg-config": executable file not found in $PATH`

**Comment by achals** [comment]
Thanks for the PR! Can you also regenerate the requirements files? There's two make commands in Makefile.

**Review by achals — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
