### PR TITLE
ci: Disable Go for Python 3.10 release

### PR DESCRIPTION
**Pull request by felixwang9817**
Signed-off-by: Felix Wang <wangfelix98@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by achals — COMMENTED** [review]
Should we try to move this to cibuildwheel at the same time? Or do we expect this to "just work" after disabling go?

**Comment by kevjumba** [comment]
> Should we try to move this to cibuildwheel at the same time? Or do we expect this to "just work" after disabling go?

@achals from our testing I think it should just work, since Felix’s build on his fork worked when gopy was disabled

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
