### PR TITLE
Tracing GRPC interceptor in serving & go sdk

### PR DESCRIPTION
**Pull request by pyalex**
**What this PR does / why we need it**:

Adding grpc interceptors to serving and go client instead of manual tracing. That would allow cross-service tracing.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
`NewTraceableGrpcClient` constructor was added to go sdk. It allows to pass Tracer on client creation phase
```

### CODE REVIEW

**Comment by woop** [comment]
@pyalex is the plan to only implement this functionality in Golang, and not Java?

**Comment by pyalex** [comment]
@woop the plan was to introduce minimal changes. do you think java sdk needs to have this functionality as well?

**Comment by woop** [comment]
> @woop the plan was to introduce minimal changes. do you think java sdk needs to have this functionality as well?

It's fine to have it only for Go, but perhaps we shouldnt document this in feast.dev but only in the API docs.

**Review by khorshuheng — APPROVED** [review]

**Pull request merged**
