### PR TITLE
fix: Broken Feature Service Link

### PR DESCRIPTION
**Pull request by nsonntag**

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by nsonntag** [comment]
@adchia I followed the instructions here to fix sign off.  But getting a "ERROR: Permission to feast-dev/feast.git denied" when pushing changes to overwrite the branch.  Any ideas?

**Comment by achals** [comment]
> @adchia I followed the instructions here to fix sign off. But getting a "ERROR: Permission to feast-dev/feast.git denied" when pushing changes to overwrite the branch. Any ideas?

@nsonntag it sounds you were trying to push to a branch in the feast repo instead of the `patch-1` branch in your fork (https://github.com/nsonntag/feast/tree/patch-1)

**Comment by nsonntag** [comment]
@adchia @achals thanks I got the sign off issue fixed.  Looks like the 'lgtm' label was removed.  Would one of you be able to add it back?

**Comment by nsonntag** [comment]
@adchia @achals thanks for the patience on this.  I was having a few different issues with sign off and signing the commits.  Looks like I have 2 workflows waiting for approval.  Only the last one needs to run.  I should finally have this all fixed.    Also looks like the 'lgtm' label was dropped again.

**Pull request merged**
