### PR TITLE
fix: Missing Catalog argument in athena connector

### PR DESCRIPTION
**Pull request by GyuminJack**
**What this PR does / why we need it**:
(simple modify) This pr is for passing argument to athena query execution

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by hemidactylus** [comment]
/lgtm

(for context: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/start_query_execution.html)

**Comment by GyuminJack** [comment]
hello. could i know when will this pr is merge?

**Pull request merged**
