### PR TITLE
Forward-port Support for Cassandra [WIP]

### LINKED ISSUE #335: Forward-port Cassandra storage support for v0.4+
#360 implemented ingestion and serving support for Cassandra, for the v0.3 series of Feast. It is considered experimental: we the implementers have not run it in production and are in the process of stress testing.

Project Namespacing (#359 and others) and async job management (#361), coming along near the same time, brought significant changes to Feast internals for v0.4. Consequently, forward-porting the Cassandra support is not trivial.

As contributors of the functionality, we are evaluating our timeline for whether we can change course for Feast v0.4+, or will need to go to production on v0.3 and update on a later schedule. In the former case, we will take on this porting task in the next 1-2 months (Jan-Feb), but in the latter case, we would welcome anyone else interested in Cassandra for v0.4+ to run with implementing it—tag @smadarasmi and @ches and we'll be happy to review, or answer questions about the existing implementation; I'm also in the public Feast Slack channel.

We will also most likely wait for dust to settle on decisions like Feature Set Versioning (#386) before we revisit the implementation.

I will update this issue accordingly when our timeline is clear.

### PR DESCRIPTION
**Pull request by Wirick**
I'm still having trouble getting the serving unit tests to pass, I think because of something that I'm not mocking, but I'm not sure. Wanted to share the work if people are interested, like @ches. I will be cleaning this up further, but I have a bit of a queue, so please be patient. This logic however seems to work well in our staging cluster right now. But want to discuss best practices and optimization

This pr ports the cassandra logic forward to be compatible with feast>=.4
Fixes #335 

```release-note
Allows for configuration of cassandra as an online serving datastore and as a job service.
```

### CODE REVIEW

**Comment by woop** [comment]
I think we should hold off on this merge before we settle: https://github.com/gojek/feast/issues/479

I think we might be able to keep the data model more consistent between old (0.3) and new (0.4+) Feast.

**Comment by ches** [comment]
A belated thanks for getting the ball rolling on this! I've been reluctant to push forward on it myself due to a few reasons I'll give below.

Couple of general remarks from my PoV when we get back 'round to this:

- Cassandra-backed job management DB is a new feature for which I'd prefer to be proposed as a separate PR.
- I'm 👎on upgrading to v4 of the Cassandra driver for Serving, [until Beam does](https://issues.apache.org/jira/browse/BEAM-6911). Unless there's a very strong reason, I feel that using different versions of significant dependencies across Feast components will ultimately bring more pain and confusion than it's worth. Dependency version declarations should probably go in the root POM's `<dependencyManagement>` as a default development practice, in hindsight we should've put the Cassandra driver's there in the original PR.

   Now, v4 finally shades its Guava dependency, which is a perennial pain and may very well qualify as "a very strong reason", but I think justification would need to be explained since v3 worked for Serving thus far, modulo the small Guava downgrade that aligned compatibility.

Coming back to what has stalled me:

- Wanting to have versions removed before touching Cassandra schema / keys again for Projects (#386, has a new RFC). This is more out of operational inertia for migrating existing deployments than worry of implementation changes, which I don't expect will be large or difficult at the storage tier. It doesn't have to block a PR like this from bringing Cassandra support to new Feast users, if they can accept that possibility that data model may change soon-ish.
- Similar but broader, #479 that @woop mentioned.
- And now, maybe aligning the implementation to #567 as that comes together.

**Comment by woop** [comment]
Just want to chime in her as well. The effort that has been put into this is very impressive @Wirick. Forward porting Cassandra support would be pretty big.

I'll into comment specifically on the PR itself at the moment, but I'll echo the reasons for delaying this forward port previously. #386 is a big change, but dare I say relatively predictable in how it will change the our APIs. #567 will hopefully add structure to this PR and others, and should not bring any big surprises. I'd argue that we would have to wait for these to both be merged in.

The biggest uncertainty for me is still which path we will take with regards to feature references and our data model, documented in #479. Getting the API right is critical. We have one more window of opportunity (with the removal of versions) to potentially make other breaking changes. If possible I'd want to come to some kind of consensus in that issue as well before merging this PR, but it probably does not have to be a blocker.

**Comment by Wirick** [comment]
@ches @woop I generally agree with everything that we've discussed. In our case because of what I was outlining in https://github.com/gojek/feast/issues/479 we've mostly abstracted the api into a centralized module called features, which can be used to create, publish and serve features using minimal feast API interaction. This means it's relatively to stay up to date as long as we change those integration points. I'm going to be keeping this current with master, because some recent changes, such as the new feature value metrics provide a lot of value, and I'm the boldly going forward type. I'm fine waiting and rebasing as development proceeds. In terms of the new drivers I've been really enjoying the new api and creation of cassandra sessions especially, and don't think that having a different dependency in ingestion outweighs the significant improvement in intuitiveness. But at the end of the day I'm flexible

**Pull request closed without merging**
