### PR TITLE
fix: Add filesystem kwargs when read prev_table on FileRetrievalJob (…

### PR DESCRIPTION
**Pull request by goodseog**
…#3490)

**What this PR does / why we need it**:
For ```FileSource``` ingest to offline store rights.

**Which issue(s) this PR fixes**:

Fixes #
Use filesystem kwargs for read dataset.
It works with local & s3fs both.

### CODE REVIEW

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Comment by felixwang9817** [comment]
@goodseog you'll need to [sign](https://docs.feast.dev/project/development-guide#signing-off-commits) your commit!

**Comment by goodseog** [comment]
Verified!
Sorry for the frequent push commits due to interworking issues with the company mail gpg key. 😂

**Comment by goodseog** [comment]
I hope ```git commit -s --amend``` works

**Comment by felixwang9817** [comment]
btw @goodseog I think your commit has been signed off properly, but there's some flakiness with our Java tests that's blocking this from merging (I've noticed this in some other PRs as well)

no need for further action on your part, once the Java tests are fixed your PR should land!

**Pull request merged**
