### PR TITLE
Fix feast apply with imported modules

### PR DESCRIPTION
**Pull request by MattDelac**
Signed-off-by: Matt Delacour <matt.delacour@shopify.com>

**What this PR does / why we need it**:
Make `feast apply` works when we import object from other files.

This is useful when we want to create a FeatureService composed of FeatureViews that have been created in other files.

_Note: FeatureServices are the only objects that need to import other feast objects like FeatureViews._

**Which issue(s) this PR fixes**:

Fixes https://github.com/feast-dev/feast/issues/1895

**Does this PR introduce a user-facing change?**:

```release-note
[Bug] `feast apply` does not raise a duplicate error when Feast objects are imported in other files
```

### CODE REVIEW

**Comment by MattDelac** [comment]
Sounds like it's impossible to really know if a module has been created within a specific file or if it has been imported.

Therefore I suggest that we only print a warning if some "Objects are duplicated". Our users can always add unit tests in their own codebase to enforce rules.
Thoughts ?

**Comment by MattDelac** [comment]
you can look at my 2 commits. The first one pass in the tests but will actually bring a silent bug that is ignoring certain feature views (tested on my use case)

**Comment by MattDelac** [comment]
Also everything I tried using the [`inspect` package](https://docs.python.org/3/library/inspect.html#retrieving-source-code) did not work

**Comment by achals** [comment]
Rather than disabling this feature, #1905 updates the logic to handle imported objects.

**Pull request closed without merging**
