### PR TITLE
fix: Remove parens from postgres source query

### PR DESCRIPTION
**Pull request by david-dest01**
**What this PR does / why we need it**:
This PR removes the parens from a query in the PostgresSQLSource which were preventing it to successfully retrieve and materialize from table references. 
 
**Was previously not supported because of bug** 
```
source=PostgreSQLSource(
    name="source_user_events_v0",
    timestamp_field="created_at",
    table="offline_store.user_events"
)
```
 
**Is now supported** 
```
source=PostgreSQLSource(
    name="source_user_events_v0",
    timestamp_field="created_at",
    table="offline_store.user_events"
)
```
```
source=PostgreSQLSource(
    name="source_user_events_v0",
    timestamp_field="created_at",
    query="select * from offline_store.user_events"
)
```
 
**Which issue(s) this PR fixes**:

Fixes #(https://github.com/feast-dev/feast/issues/3804)

### CODE REVIEW

**Comment by david-dest01** [comment]
@achals lmk if you need anything else here

**Comment by achals** [comment]
@david-dest01 Do you mind fixing DCO? https://github.com/feast-dev/feast/pull/3807/checks?check_run_id=17817796280

**Comment by achals** [comment]
Looks good to me otherwise

**Comment by job-almekinders** [comment]
Hey all, I've opened a similar PR #4026.

If any one of you has the time to take a look this would be highly appreciated! @achals @sudohainguyen

**Pull request closed without merging**
