### PR TITLE
feat: Allow feast snowflake to read in byte string for private-key authentication

### PR DESCRIPTION
**Pull request by arturkolakowski**
# What this PR does / why we need it:

Allows the user to pass private_key as a byte string for Snowflake key-pair authentication rather than only limiting the ability to refer to the file path where the private key is stored. 
Gives the ability to pass in `private_key` from a Secret Manager service (i.e: Google Cloud Secret Manager) 

# Which issue(s) this PR fixes:

# Fixes

### CODE REVIEW

**Comment by tokoko** [comment]
just curious, are you able to set bytes value from yaml as well or will this only work in python?

**Comment by arturkolakowski** [comment]
> just curious, are you able to set bytes value from yaml as well or will this only work in python?

yes it will work, for example, `feature_store.yaml` can include `private_key` of format 
```
'-----BEGIN ENCRYPTED PRIVATE KEY-----
.
.
-----END ENCRYPTED PRIVATE KEY-----'
```

**Comment by tokoko** [comment]
Wouldn't that be interpreted as a string and therefore as a file path?

**Comment by arturkolakowski** [comment]
As I am looking through the code base and considering this example: `SnowflakeOfflineStore`
`SnowflakeOfflineStore` establishes a snowflake connection with GetSnowflakeConnection (`/feast/infra/utils/snowflake/snowflake_utils.py`)
```
with GetSnowflakeConnection(config.offline_store) as conn:
            snowflake_conn = conn
```
when `parse_private_key_path` gets called `private_key` is already of type `bytes` so this way only works in python, my apologies.

**Comment by tokoko** [comment]
@arturkolakowski how about we add another field in config instead (something like `private_key_content`) which would simply take precedence?

**Comment by arturkolakowski** [comment]
@tokoko Made changes based on the request

**Review by tokoko — APPROVED** [review]
lgtm, thanks

**Pull request merged**
