### PR TITLE
fix: Issue-3771, fix document error as not shortcut -f option in code.

### LINKED ISSUE #3771: No such option: -f for feast CLI
## Expected Behavior 

According to documentation:
https://docs.feast.dev/how-to-guides/feast-snowflake-gcp-aws/structuring-repos
```
feast -f staging/feature_store.yaml apply
```
should work

## Current Behavior

```
Usage: feast [OPTIONS] COMMAND [ARGS]...
Try 'feast --help' for help.

Error: No such option: -f
```
### Specifications

- Version: 0.34.1
- Platform: Linux
- Subsystem:

### PR DESCRIPTION
**Pull request by shuchu**
**What this PR does / why we need it**:
The code in cli.py (line 75) doest not configure shortcut:
`@click.option(
    "--feature-store-yaml",
    help="Override the directory where the CLI should look for the feature_store.yaml file.",
)`

**Which issue(s) this PR fixes**:

Fixes #3771

### CODE REVIEW

**Review by achals — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by achals** [comment]
@shuchu You need to sign off your commits: https://github.com/feast-dev/feast/pull/3783/checks?check_run_id=17532312440

**Comment by shuchu** [comment]
sorry about this mistake. Have fixed it.

**Review by redhatHameed — APPROVED** [review]
FYI @etirelli for merge

**Pull request closed without merging**
