### PR TITLE
feat: Custom schema for SQL Registry

### PR DESCRIPTION
**Pull request by zerafachris**
**What this PR does / why we need it**:
Current SQL Registry uses public schema. This provides a **registry_schema** inside of config_yaml that will use _registry_schema_ for all registry related tables.

**Which issue(s) this PR fixes**:
https://github.com/feast-dev/feast/issues/3568

Fixes #[3568](https://github.com/feast-dev/feast/issues/3568)

### CODE REVIEW

**Comment by adamschmidt** [comment]
Have you considered using the `db_schema` property that's in the [pgsql connection config properties](https://github.com/feast-dev/feast/blob/2c04ec175f9155c906f90502bffe1bd5a5619ddb/sdk/python/feast/infra/utils/postgres/postgres_config.py#L12)? This same configuration class is used for the online store, so this should work too.

Adding a specific schema name seems redundant if you use this.

**Comment by zerafachris** [comment]
Hi @adamschmidt , the feature handles the metadata object inside of PostGres. I can use **_db_schema_**  instead of **_registry_schema_** no worries, however the class model is not being used.  All objects that are supplied in the config are parsed independently.

**Comment by zerafachris** [comment]
@adamschmidt bump re above ☝️

**Comment by adchia** [comment]
Assigning to @achals since he's more familiar with this code!

**Comment by zerafachris** [comment]
Conflicts have been resolved. Can we get a review

**Comment by zerafachris** [comment]
Hi @achals , do you think we can get a peer review? I do not wish to stay resyncing with master branch and resolve conflicts again.

**Comment by jeremyary** [comment]
Hi @zerafachris, with new maintainers in place we're making best efforts to try and resolve long-standing conversations such as what you've encountered here. With that in mind, we'd still have a few things to work through prior to merging your contribution. As a start, our DCO check indicates [here](https://github.com/feast-dev/feast/pull/3575/checks?check_run_id=15427097214) some fixes that are needed. If you're still interested in persuing the PR, please take a look at this & other running checks. Thanks!

**Pull request closed without merging**
