### PR TITLE
Add IngestionId & EventTimestamp to FeatureRowBatch to calculate lag metric correctly

### PR DESCRIPTION
**Pull request by pyalex**
**What this PR does / why we need it**:

Currently row based metrics (like lag) are calculated incorrectly due to absence of correct timestamp in FeatureRow.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by woop** [comment]
Good feedback that we have received in the past is that we should be updating the release note with the bug as well as mentioning when the bug was introduced.

**Comment by pyalex** [comment]
> Good feedback that we have received in the past is that we should be updating the release note with the bug as well as mentioning when the bug was introduced.

So metrics on BQ never worked, since it didn't produce output before 0.6. But we can say that bug was introduced with 0.6

**Pull request merged**
