### PR TITLE
docs: Improve release process notes

### PR DESCRIPTION
**Pull request by adchia**
Signed-off-by: Danny Chiao <danny@tecton.ai>

**What this PR does / why we need it**:
There are some missing pieces of the release notes. Also added more verification steps and documentation on how to maintain maintenance releases (older branches)
**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
