### PR TITLE
Remove and update deprecation functions

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:
This PR removes functions from Python SDK which have been marked to be deprecated in future releases.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Users should use get_historical_features instead of get_batch_features, and only pass in list of dictionaries for get_online_features instead of passing in proto EntityRow.
```

### CODE REVIEW

**Comment by mrzzy** [comment]
Since we are using a new API, maybe we should be switching SDKs?

https://github.com/terryyylim/feast/blob/f004268d7d03e10d696d1adf53661934b03a8e6c/infra/charts/feast/templates/tests/test-feast-online-serving.yaml#L18

**Review by khorshuheng — APPROVED** [review]

**Pull request merged**
