### PR TITLE
fix: Removed the k8s dependency from required dependencies

### PR DESCRIPTION
**Pull request by redhatHameed**
# What this PR does / why we need it:

The k8s dependency already added into extra dependency section as it's not mandatory so removed from required dependencies.

# Which issue(s) this PR fixes:

# Misc

### CODE REVIEW

**Comment by tokoko** [comment]
@redhatHameed move this [import](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/permissions/server/utils.py#L14) inside a function so that it's invoked only if k8s is set as an auth type.

**Comment by redhatHameed** [comment]
> @redhatHameed move this [import](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/permissions/server/utils.py#L14) inside a function so that it's invoked only if k8s is set as an auth type.

@tokoko thanks for direction, updated accordingly and all tests are passing now.

**Comment by tokoko** [comment]
This should be good. Can you update the lock files as well?

**Comment by redhatHameed** [comment]
> This should be good. Can you update the lock files as well?

this is the make command for that right `lock-python-dependencies-all`

**Comment by tokoko** [comment]
yup

**Comment by redhatHameed** [comment]
> yup

Thanks updated, please have look

**Review by tokoko — APPROVED** [review]
lgtm

**Pull request merged**
