### PR TITLE
[WIP] loosen protobuf version constraints

### PR DESCRIPTION
**Pull request by cburroughs**
[force version for tests]

Signed-off-by: Chris Burroughs <chris.burroughs@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by kevjumba** [comment]
@cburroughs Hey Chris! Why are you pinning the protobuf version? This seems to do the opposite of what your pr title is describing.

**Comment by kevjumba** [comment]
> @cburroughs Hey Chris! Why are you pinning the protobuf version? This seems to do the opposite of what your pr title is describing.

Also, on that front, I think our general motto is to not pin critical packages to specific versions unless absolutely necessary. I'm going to close this pr. Please feel free to reopen with a specific issue that you want resolved.

**Comment by achals** [comment]
I believe the pin was for testing. @cburroughs mentioned this in the community call/slack a couple of days ago.

**Comment by cburroughs** [comment]
On  2022-08-18  13:46, Kevin Zhang wrote:
> @cburroughs Hey Chris! Why are you pinning the protobuf version? This seems to do the opposite of what your pr title is describing.

Hi! This is my first time trying to do something with the feast codebase 
and protobuf version have a strong 'here be dragons' vibe.  As I 
understand it there is specific code (#2484) that interacts with version 
3.20.0+.

My rough plan was to:
  * Verify that with 3.19, some tests fail.
  * Modify code to work with <3.19 and >3.19.
  * Verify tests pass with both.

That might not be viable, or maybe tensorflow and friends will update 
their protobuf version faster and render this line of inquiry obsolete. 
This PR was currently on the first step (and not yet successful as I 
didn't understand the interaction between the versions in setup.py and 
the .txt files).

**Comment by felixwang9817** [comment]
@cburroughs I think #3103 actually resolves your issue?

**Comment by cburroughs** [comment]
> @cburroughs I think https://github.com/feast-dev/feast/pull/3103 actually resolves your issue?

Fantastic! Thank you.

**Pull request closed without merging**
