### PR TITLE
chore: Change arrow scalar ids usage

### PR DESCRIPTION
**Pull request by camenares**
[PENDING] 2. Run unit tests and ensure that they are passing: https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md#unit-tests

# What this PR does / why we need it:

Changes where `_ARROW_SCALAR_IDS_TO_BQ` is imported, so that `google-cloud-bigquery` can be bumped. This PR only bumps to 3.13.0, but unblocks further bumping. `_ARROW_SCALAR_IDS_TO_BQ` was moved [here](https://github.com/googleapis/python-bigquery/pull/1679/files).

# Which issue(s) this PR fixes:
Related to https://github.com/feast-dev/feast/issues/3823, but provides a different solution than downgrading.

### CODE REVIEW

**Comment by tokoko** [comment]
This will break all versions below 3.14, won't it? Maybe we should just copy the mapping over instead... Not ideal, but might be better than to depend on an internal helper function. @sudohainguyen wdyt?

**Comment by sudohainguyen** [comment]
good fix!
@camenares could you help re-generate the requirements txt files?
to make sure all other packages are compatible 😄

**Comment by sudohainguyen** [comment]
please also check that the change is backward compatible for those who using version less that 3.12

**Comment by camenares** [comment]
@tokoko that's a good point, I think you're right, it would not work 3.12 (but will double check). 

I think there's three options:

1. Change `setup.py` to also strict pin to `3.13.0`
2. Do a try/catch and try to import from each helper
3. Copy the mapping over.

I will work on regenerating the requirements.txt's

**Comment by tokoko** [comment]
@camenares option 2 also sounds good to me. We can resort to copying the mapping if some other issue arises in the future. Any reason for the upper bound set at `<3.14`. Why can't we change to `<4`? Are there some other known issues?

P.S. You need to sign all your commits (`git commit -s`). Follow the instructions [here](https://github.com/feast-dev/feast/pull/4347/checks?check_run_id=27388388106) to fix the DCO check.

**Comment by tokoko** [comment]
Can you run `make lint-python` and `make format-python` commands?

**Comment by camenares** [comment]
@tokoko yep! Fixing that now, I believe it's related to https://github.com/python/mypy/issues/1153 but testing this locally

**Comment by camenares** [comment]
@tokoko I also noticed that allowing the bound to be `<4` failed the full integration tests (local were fine). Restricting to `<3.14.0` seems to let those pass though.

**Comment by tokoko** [comment]
@camenares integration tests failure was unrelated, sorry about that. We accidentally merged a failing PR to master.

**Comment by camenares** [comment]
@tokoko Oh! Thanks for that, I just figured it was worth trying `<3.14`. Let me bump to `<4.0` again then.

**Comment by tokoko** [comment]
You will have to regenerate requirements files for the bump to take effect in ci.

**Comment by camenares** [comment]
@tokoko `<4.0` worked! I see no additional changes after running `make lock-python-dependencies-all`.

**Review by tokoko — APPROVED** [review]
right, looks like `firebase-admin` lib is pinning with an upper bound, I'll look into that later. lgtm otherwise, thanks a lot

**Comment by camenares** [comment]
Thanks a lot for the guidance @tokoko , looking forward to more Feast contributions in the future!

**Comment by tokoko** [comment]
we have some strict rate limits on cloud services that our tests are often hitting, you can ignore it.

**Pull request merged**
