### PR TITLE
Bump fastavro version

### LINKED ISSUE #1584: Bump fastavro version
**Is your feature request related to a problem? Please describe.**
The version of Fastavro that we're using is kinda old and may be buggy soon. It's also causing some version conflicts with packages that have already upgraded to the newer (1.xx) versions.

**Describe the solution you'd like**
Bump Fastavro to 1.x.x

### PR DESCRIPTION
**Pull request by kevinhu**
**What this PR does / why we need it**:
Bumps fastavro 
**Which issue(s) this PR fixes**:

Fixes #1584 

**Does this PR introduce a user-facing change?**:

```release-note
Bump fastavro version from '>=0.22.11,<0.23' to '>=1.1.0'
```

### CODE REVIEW

**Comment by achals** [comment]
@kevinhu could you address the DCO check and add a release note in the pr description? Looks good otherwise.

**Comment by kevinhu** [comment]
Done!

**Comment by kevinhu** [comment]
I think the check isn't running correctly – it seems that both the commits have been signed (including the one in question, https://github.com/feast-dev/feast/pull/1585/commits/89aece1519b0d0386abdaea8b0cc88b193b27786), but DCO isn't picking up on it.

**Comment by achals** [comment]
> I think the check isn't running correctly – it seems that both the commits have been signed (including the one in question, [89aece1](https://github.com/feast-dev/feast/commit/89aece1519b0d0386abdaea8b0cc88b193b27786)), but DCO isn't picking up on it.

Hmmm, the commit in question doesn't seem to have the `Signed-off-by` like the other commit: https://github.com/feast-dev/feast/pull/1585/commits/6813f87d1978cb99da2d459f482e24368f0b64c3

image
image

**Comment by kevinhu** [comment]
Fixed now

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
