### PR TITLE
fix: Make name a keyword arg for the Entity class

### PR DESCRIPTION
**Pull request by achals**
Signed-off-by: Achal Shah <achals@gmail.com>

**What this PR does / why we need it**:
This change is backwards compatible, but produces a deprecation warning if the name is specified as a positional arg to the `__init__` method.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by kevjumba** [comment]
Resstarted the java tests

**Comment by kevjumba** [comment]
@achals There seems to be a build issue with the java integration tests.

**Comment by achals** [comment]
> @achals There seems to be a build issue with the java integration tests.

Ugh yeah. Same failure in https://github.com/feast-dev/feast/runs/5759198528?check_suite_focus=true.

**Comment by achals** [comment]
> @achals There seems to be a build issue with the java integration tests.

Fixed by #2469

**Pull request merged**
