### PR TITLE
feat: Add local tests for s3 registry using minio

### PR DESCRIPTION
**Pull request by tokoko**
**What this PR does / why we need it**:
S3 registry is currently impossible to test locally, as all tests depend on the presence of an aws account credentials. This PR adds local S3 registry tests using minio.

### CODE REVIEW

**Comment by HaoXuAI** [comment]
I use to use localstack(https://www.localstack.cloud/) for local testing, what's the difference with the Minio?

**Comment by tokoko** [comment]
@HaoXuAI Minio is s3-compatible object storage, not just for testing though, it's actually used out there in the wild. localstack is obviously a lot more broad, but only for testing.

**Comment by franciscojavierarceo** [comment]
this lgtm @HaoXuAI any hesitation here?

**Review by HaoXuAI — APPROVED** [review]
LGTM

**Pull request merged**
