### PR TITLE
Allow Feast apply to import files recursively (and add .feastignore)

### PR DESCRIPTION
**Pull request by tsotnet**
Signed-off-by: Tsotne Tabidze <tsotne@tecton.ai>

**What this PR does / why we need it**: We add functionality to `feast apply` to recursively look into the feature repo and import all files to find Feast Objects for apply. Also, we add `.feastignore` file where users can define which paths to ignore (similar to `.gitignore`). This format can understand comments (with #) and matches (* and **).

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
* `feast apply` will recursively parse files in feature repo sub directories
* `.feastignore` will allow defining paths to ignore during `feast apply`, similarly to `.gitignore`
```

### CODE REVIEW

**Review by jklegar — APPROVED** [review]

**Comment by jklegar** [comment]
only comment is to document this functionality, but if you want to do it in a separate diff feel free to merge

**Comment by woop** [comment]
> only comment is to document this functionality, but if you want to do it in a separate diff feel free to merge

I agree. Aside from @oavdeev's comment the only thing that is missing is documentation. Would you mind adding a page under `Reference` in our documentation to describe the functionality of `.feastignore`? We should probably also mention the `.feastignore` in the [Feature Repository](https://docs.feast.dev/concepts/feature-repository) section.

**Comment by tsotnet** [comment]
@woop If I understood correctly, I need to go through the documentation changes through GitBook. If so, let's merge this independently.

**Review by woop — APPROVED** [review]

**Pull request merged**
