### PR TITLE
fix: Remove extra quoting in snowflake python connection

### PR DESCRIPTION
**Pull request by esadler-hbo**
Signed-off-by: Evan <evan.sadler@warnermedia.com>

**What this PR does / why we need it**:
Possible extra quotes. Need to verify by running integration tests.

**Which issue(s) this PR fixes**:
https://github.com/feast-dev/feast/issues/2595

Fixes #

### CODE REVIEW

**Comment by esadler-hbo** [comment]
/assign @woop

I noticed an issue for me, but obviously the quotes could be important for somethings.  I was hoping to throw up a PR that would run the python integration test suite. 

Also let me know if you have ideas on how to test this more officially than editing the repo locally. I'm sure it is possible, but I am new to this repo!

**Comment by achals** [comment]
@sfc-gh-madkins If I remember correctly you added this quite recently, could you take a look?

@esadler-hbo do you mind adding a test or something that reproduces the issue in #2595 without this patch?

**Comment by sfc-gh-madkins** [comment]
would be great to understand what your feature_store.yaml / config file looks like?

**Comment by esadler-hbo** [comment]
> would be great to understand what your feature_store.yaml / config file looks like?

I could totally be doing this wrong, but this is what I had. I did not use quotes for any of the filled in values. 
```yaml
# feature_store.yaml
project: firm_finch
registry: registry.db
provider: local
offline_store:
    type: snowflake.offline
    account: 
    user: 
    password: 
    role:
    warehouse:
    database:
    schema:
    config_path: "local path/config.ini"
```
The config file
```ini
[connections.feast_offline_store]
private_key_passphrase = phrase
private_key = path_to_key
```

**Comment by esadler-hbo** [comment]
> @sfc-gh-madkins If I remember correctly you added this quite recently, could you take a look?
> 
> @esadler-hbo do you mind adding a test or something that reproduces the issue in #2595 without this patch?

Happy to add a test once @sfc-gh-madkins lets me know if my config setup makes sense. I just need to get setup with a test environment and then getting some direction to where and how be much appreciated.

**Comment by sfc-gh-madkins** [comment]
my guess is you are not respecting case sensitivity -- most likely your warehouse is ALL CAPS in Snowflake but you are putting it in lowercase in your config file

Currently feast is using double quoted identifier syntax -- see https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html

i appreciate that this is not documented well in the feast docs

**Comment by esadler-hbo** [comment]
> my guess is you are not respecting case sensitivity -- most likely your warehouse is ALL CAPS in Snowflake but you are putting it in lowercase in your config file
> 
> Currently feast is using double quoted identifier syntax -- see https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html
> 
> i appreciate that this is not documented well in the feast docs

Well I reset my environment and I couldn't reproduce the issue. Sorry to bother you all!

**Pull request closed without merging**
