### PR TITLE
docs: Fix proto docstring typo

### PR DESCRIPTION
**Pull request by loftiskg**
**What this PR does / why we need it**:

I think this might be a typo.

### CODE REVIEW

**Comment by kevjumba** [comment]
@loftiskg can you sign the commits

**Comment by loftiskg** [comment]
@kevjumba sure thing.  Pushed an amended commit with the signoff

**Comment by loftiskg** [comment]
I am also not sure why the linting CI step is failing here

**Review by achals — APPROVED** [review]

**Pull request merged**
