### PR TITLE
feat: Adding get_online_features_async to feature store sdk

### LINKED ISSUE #3927: Add async variant of `get_online_features`
**Is your feature request related to a problem? Please describe.**
Putting feast's python online store interface in production is a hard sell as it is, but the fact what there's no way to make it async makes it even harder. Using `get_online_features` with good online store implementation might be suitable for services with relatively low traffic, but there comes a point beyond which it's hard to scale.

**Describe the solution you'd like**
Add `get_online_features_async` method to `FeatureStore` class. The method will either use new `online_read_async` method from the configured online store or throw an exception if the online store doesn't implement async variant.  

**Describe alternatives you've considered**
The alternative is to forgo this, treat python `get_online_features` as something that comes with practical limitations and focus on developing the alternatives in other languages, for example java feature server.

**Additional context**
I admit I haven't really done any benchmarking to compare the alternatives, the claims are mostly just common sense conclusions, but I'll gladly be corrected if others disagree.

### PR DESCRIPTION
**Pull request by breno-costa**
# What this PR does / why we need it:

# Which issue(s) this PR fixes:

Closes #3927

### CODE REVIEW

**Comment by tokoko** [comment]
@breno-costa thanks, I'll take a closer look tomorrow. One comment right now is that we will probably need to add a test for async under online_store in integration tests as well. Tests will have to marked to be skipped for every online store other than redis for now. We can probably defer it for separate PR (?) if you like but it'll be essential eventually.

**Comment by breno-costa** [comment]
I'm running some benchmarks to check latency and throughput for this new implementation.

Just created a benchmark repo with a FastAPI application with sync and async endpoints. 
https://github.com/breno-costa/feast-benchmark-async-sdk

Here are some initial results. Don't take them as final results, as I'm still analyzing them. If you have any comments on benchmark repository, please let me know.

Sync implementation
```python
wrk --threads 4 --duration 1m --latency "http://localhost:8000/get_online_features"
Running 1m test @ http://localhost:8000/get_online_features
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    51.38ms    5.03ms 120.58ms   91.66%
    Req/Sec    38.87      5.37    60.00     85.10%
  Latency Distribution
     50%   50.51ms
     75%   52.12ms
     90%   54.81ms
     99%   68.71ms
  9343 requests in 1.00m, 18.91MB read
Requests/sec:    155.56
Transfer/sec:    322.37KB
```

Async implementation
```python
wrk --threads 4 --duration 1m --latency "http://localhost:8000/get_online_features_async"
Running 1m test @ http://localhost:8000/get_online_features_async
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    33.67ms    4.86ms 104.30ms   88.98%
    Req/Sec    59.56      6.50    80.00     72.19%
  Latency Distribution
     50%   33.12ms
     75%   34.52ms
     90%   37.08ms
     99%   48.33ms
  14284 requests in 1.00m, 28.91MB read
Requests/sec:    237.67
Transfer/sec:    492.52KB
```

**Comment by tokoko** [comment]
that's really useful, I had something like that at the back of my mind. Can I suggest to change fastapi endpoint for sync `get_online_features` from async to sync? Doing a sync processing behind an async endpoint comes with a performance penalty.

**Comment by breno-costa** [comment]
> that's really useful, I had something like that at the back of my mind. Can I suggest to change fastapi endpoint for sync `get_online_features` from async to sync? Doing a sync processing behind an async endpoint comes with a performance penalty.

Thanks for the heads up. I changed and made a lot of difference. The event loop added some overhead and degraded the performance for sync endpoint. I replaced old values with new ones in last comment. 

That said, I didn't see many difference for sync and async implementations for this basic benchmark case. I'll run same script with more features and entities to increase time taken to fetch data from Redis. Maybe add some CPU-bound operation after fetching data to simulate more ML like scenario.

**Comment by tokoko** [comment]
That's strange 😄 cpu-bound operations will degrade async performance even more, actually. And it's not that realistic of a scenario anyway, one would normally put this async retrieval behind a separate feature server where model inference doesn't take place. one caveat here is that redis in your benchmarks is a local one, so network latency doesn't play as much role. With a remote redis, async will do better, not sure how significantly that would change the picture though.

P.S. another idea that might help... can you also benchmark pure `OnlineStore.read(..)` calls rather than `get_online_features`? There's a lot of crazy stuff going on in `get_online_features`, maybe they are the culprit.

**Comment by breno-costa** [comment]
@tokoko I've materialized data into a Redis instance on Google Cloud to test this implementation. The server is accessing the Redis instance through a ssh tunnel intentionally to increase network latency. Also increased the number of connections (or users) in my benchmark.  When I simulated such kind of scenario, I started to see the benefits of async implementation. Example here:

```python
~ wrk --threads 4 --connections 200 --duration 1m --latency "http://localhost:8000/get_online_features"
Running 1m test @ http://localhost:8000/get_online_features
  4 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.83s   981.20ms   4.65s    71.63%
    Req/Sec    42.35     35.19   160.00     55.26%
  Latency Distribution
     50%    2.32s
     75%    3.55s
     90%    4.31s
     99%    4.49s
  4160 requests in 1.00m, 8.41MB read
  Socket errors: connect 0, read 149, write 0, timeout 0
Requests/sec:     69.23
Transfer/sec:    143.32KB
```

```python
~ wrk --threads 4 --connections 200 --duration 1m --latency "http://localhost:8000/get_online_features_async"
Running 1m test @ http://localhost:8000/get_online_features_async
  4 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29s    66.51ms   1.56s    72.30%
    Req/Sec    42.91     24.80   151.00     69.87%
  Latency Distribution
     50%    1.28s
     75%    1.32s
     90%    1.38s
     99%    1.51s
  9206 requests in 1.00m, 18.61MB read
  Socket errors: connect 0, read 142, write 0, timeout 0
Requests/sec:    153.21
Transfer/sec:    317.18KB
```

**Comment by breno-costa** [comment]
> Tests will have to marked to be skipped for every online store other than redis for now. We can probably defer it for separate PR (?) if you like but it'll be essential eventually.

I can manage that in another PR if you don't mind.

**Review by tokoko — APPROVED** [review]
sure, lgtm. thanks

**Comment by breno-costa** [comment]
Could you add that label to run tests? I can't add it.

**Comment by tokoko** [comment]
pretty sure integration tests are still broken, so no point yet :) (#4171). @jeremyary Can you add the label here once credentials are in order?

**Comment by jeremyary** [comment]
@tokoko yep, will do. Credentials PR is green now, so hopefully shouldn't be much longer!

**Comment by franciscojavierarceo** [comment]
@tokoko actually should just be able to rerun jobs. I just kicked it off.

**Comment by breno-costa** [comment]
I could finally reproduce the error locally.
There is a difference between sync and async results for timestamp values. I'm investigating that right now.

**Comment by breno-costa** [comment]
Everything is sorted now. All green checks 😄 
How do you want to proceed with this PR? @tokoko @franciscojavierarceo

**Review by tokoko — APPROVED** [review]
lgtm. we can merge this

**Comment by franciscojavierarceo** [comment]
Awesome stuff, thanks @breno-costa!!!

**Pull request merged**
