### PR TITLE
fix: Fix on demand feature view crash from inference when it uses df.apply

### PR DESCRIPTION
**Pull request by adchia**
**What this PR does / why we need it**:
Feast did schema inference on on demand transforms by passing in an empty dataframe to the UDF with the same expected columns.

This can cause a crash though if it uses dataframe.apply. Example:

```bash
File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3602, in __setitem__
    self._set_item_frame_value(key, value)
  File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3742, in _set_item_frame_value
    self._set_item_mgr(key, arraylike)
  File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3754, in _set_item_mgr
    self._mgr.insert(len(self._info_axis), key, value)
  File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1162, in insert
    block = new_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1937, in new_block
    check_ndim(values, placement, ndim)
  File "/Users/dannychiao/.pyenv/versions/python-3.8/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1979, in check_ndim
    raise ValueError(
ValueError: Wrong number of items passed 8, placement implies 1
```

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by achals** [comment]
TIL about df.apply.

/lgtm

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
