### PR TITLE
fix: Buggy SQL for postgres source

### PR DESCRIPTION
**Pull request by xaniasd**
**What this PR does / why we need it**:

Removes parentheses that lead to SQL syntax error when calling `get_table_column_names_and_types`

**Which issue(s) this PR fixes**:

No corresponding issue created.

### CODE REVIEW

**Comment by achals** [comment]
@xaniasd do you have a stack trace of the error that manifests with the parentheses?

**Comment by xaniasd** [comment]
hi @achals 
in order to reproduce the bug, you need a PostgreSQLSource specifying a table instead of a query. Then the error shows up e.g. with `feast plan`. Using feast 0.27.1 btw. Hope this helps!

```
Traceback (most recent call last):
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/cli.py", line 497, in plan_command
    plan(repo_config, repo, skip_source_validation)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/repo_operations.py", line 217, in plan
    registry_diff, infra_diff, _ = store.plan(repo)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/usage.py", line 299, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/usage.py", line 288, in wrapper
    return func(*args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/feature_store.py", line 724, in plan
    self._make_inferences(
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/feature_store.py", line 602, in _make_inferences
    update_feature_views_with_inferred_features_and_entities(
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/inference.py", line 168, in update_feature_views_with_inferred_features_and_entities
    _infer_features_and_entities(
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/inference.py", line 206, in _infer_features_and_entities
    table_column_names_and_types = fv.batch_source.get_table_column_names_and_types(
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/dimitris.stafylarakis/Library/Caches/pypoetry/virtualenvs/feast-test-repo-iTsfB37N-py3.9/lib/python3.9/site-packages/feast/infra/offline_stores/contrib/postgres_offline_store/postgres_source.py", line 114, in get_table_column_names_and_types
    cur.execute(
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: SELECT * FROM (driver_hourly_stats) AS sub LIMIT 0
                                          ^                                     
```

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by xaniasd** [comment]
hi @adchia some integration tests failed after your last approval (unrelated to the code change as far as I could tell) so I forced them to run again. I'm not really familiar with the build system but they seem to be ok now, can you approve again please?

**Comment by xaniasd** [comment]
@adchia thanks, still failing on the go linting check. What do you suggest?

**Comment by adchia** [comment]
i believe this is a build breakage that @felixwang9817 is investigating

**Comment by xaniasd** [comment]
ok I'll wait for the fix then :+1:

**Pull request merged**
