### PR TITLE
feat: Qdrant vectorstore support

### PR DESCRIPTION
**Pull request by Anush008**
## Description

This PR adds support for Qdrant - https://qdrant.tech to be used as a vectorstore in Feast.

### CODE REVIEW

**Comment by HaoXuAI** [comment]
If possible, would you mind showing a screenshot or copying/pasting your integration test with the Qdrant vector store result?

**Comment by Anush008** [comment]
Hi @HaoXuAI
Screenshot 2024-10-26 at 11 26 17 AM

This runs the ingest and retrieval tests inside `tests/integration/online_store/test_universal_online.py::test_retrieve_online_documents`

I had to use the `environment` fixture instead of `vectordb_environment` with `entity_key_serialization_version=3`.

**Comment by HaoXuAI** [comment]
Correct, that's a bug with vectordb_environment I haven't got time to fix it.
Great work. thanks!

**Review by HaoXuAI — APPROVED** [review]

**Review by franciscojavierarceo — APPROVED** [review]

**Comment by HaoXuAI** [comment]
The failed test is irrelevant to the pr. merging it now.

**Comment by franciscojavierarceo** [comment]
Hi @Anush008 we implemented a more generic API in `read_online_documents_v2` as well as an example for `online_read` with Milvus.

I wanted to reach out and see if you'd be interested in updating to support broader retrieval? 

The benefit of this is allowing for more general purpose retrieval along with vector search. 

I also plan to incorporate Feast into Llama Stack so Qdrant would benefit from the integration. It's also a much easier integration now. Let me know!

**Pull request merged**
