### PR TITLE
Only apply FVs which have changed

### PR DESCRIPTION
**Pull request by judahrand**
Signed-off-by: Judah Rand <17158624+judahrand@users.noreply.github.com>

**What this PR does / why we need it**:
Currently, when `feast apply` is called all FeatureViews are applied whether or not they already exist in an unchanged state. This seems to wipe the `materialization_intervals` attribute which necessitates a full materialization. I have at least one FV which takes on the order of 4hrs to sync which causes issues.

This PR identifies FVs which already exists and does not apply them again.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
Only apply FeatureViews which have changed when calling `feast apply`.
```

### CODE REVIEW

**Comment by judahrand** [comment]
AWS failure in the integration tests.

**Comment by pyalex** [comment]
Hi @judahrand, thanks for your PR. Can you please add a test with this use case that is currently failing for you?

**Comment by judahrand** [comment]
> Hi @judahrand, thanks for your PR. Can you please add a test with this use case that is currently failing for you?

Not easily, no. If you'd like to add a framework for testing the CLI I'll happily add a test case.

**Comment by judahrand** [comment]
Huh, on further inspection this is not an issue. I'll try to work out what caused the problem I ran into.

**Pull request closed without merging**
