### PR TITLE
allow https url for spark ingestion jar

### PR DESCRIPTION
**Pull request by jklegar**
Signed-off-by: Jacob Klegar <jacob@tecton.ai>

**What this PR does / why we need it**: previously if the spark ingestion jar was a https url (which is the default), ingestion would fail because Feast would try to read and upload the jar as if the url were a local path

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by woop** [comment]
@jklegar so this change doesn't apply to dataproc?

**Comment by jklegar** [comment]
I believe on dataproc https should already work due to https://github.com/feast-dev/feast/blob/eaaf23372db7b85d27194e6fdbe9f109f30f7c7c/sdk/python/feast/pyspark/launchers/gcloud/dataproc.py#L278

**Review by oavdeev — APPROVED** [review]

**Pull request merged**
