### PR TITLE
Add job-controller to test containers

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:
`latest` tag is updated for each versioned tag, and in the latest version 0.7.0-rc.3, job-controller is separated from core, requiring it to be included in the test containers.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by woop** [comment]
Is there a github issue attached to this problem?

**Comment by terryyylim** [comment]
> Is there a github issue attached to this problem?

Nope there isn't.

**Review by woop — APPROVED** [review]

**Pull request merged**
