### PR TITLE
chore: Remove gcp requirement for local tests

### PR DESCRIPTION
**Pull request by felixwang9817**
**What this PR does / why we need it**: This PR allows unit tests to be run (`make test`) without any GCP credentials, which were previously required. It also adds several new example feature repos, as previously many tests would share the same feature repo, making it very hard to reason about how each test used the repo.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by achals — APPROVED** [review]
/lgtm

**Comment by adchia** [comment]
Need to rebase?

**Comment by felixwang9817** [comment]
yeah @adchia am working on rebase

**Review by kevjumba — APPROVED** [review]
/lgtm

**Pull request merged**
