### PR TITLE
fix: Add getter/setter for RestServer

### PR DESCRIPTION
**Pull request by yongheng**
**What this PR does / why we need it**:

The error below occurs when we start Java Server:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "rest" (class feast.serving.service.config.ApplicationProperties), not marked as ignorable (2 known properties: "feast", "grpc"])
```

This PR fixes it.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by adchia** [comment]
I think the RestServer doesn't actually do anything? We should probably just remove all references to it instead

**Comment by yongheng** [comment]
> I think the RestServer doesn't actually do anything? We should probably just remove all references to it instead

I didn't try to understand what the RestServer does too much and just wanted to make the error go away. Please feel free the close this PR if you decide to remove all references to it. Thanks!

**Pull request closed without merging**
