### PR TITLE
fix: More explicit error messages

### LINKED ISSUE #2696: Better and more explicit Pydantic error messages
**Is your feature request related to a problem? Please describe.**
The Pydantic errors can be very annoying to debug when the error messages are not explicit or (as often seen) completely missing. I provide two specific examples bellow but many more can be found throughout the codebase.

**Describe the solution you'd like**
Always include explicit error messages to all Pydating validation checks.

**Additional context**

A couple of examples:

```pycon
>>> from feast import RepoConfig
>>> repo_config = RepoConfig(
...     project="foo",
... )
Traceback (most recent call last):
  File "my_script.py", line 2, in <module>
    repo_config = RepoConfig(
  File ".venv/lib/python3.9/site-packages/feast/repo_config.py", line 124, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RepoConfig
__root__
   (type=assertion_error)
```

👆 In this example, the `feast.errors.FeastProviderNotSetError` exception should be raised instead of a blank AssertionError. The error message here would be explicit (i.e. `"Provider is not set, but is required"`)

```pycon
>>> from feast import RepoConfig
>>> repo_config = RepoConfig(
...     project="foo",
...     provider="local",
...     offline_store=dict(
...         type="my.custom.offline_store.CustomStore"
...     ),
... )
Traceback (most recent call last):
  File "my_script.py", line 2, in <module>
    repo_config = RepoConfig(
  File ".venv/lib/python3.9/site-packages/feast/repo_config.py", line 124, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RepoConfig
__root__
   (type=assertion_error)
```

👆 Just like in the other example, it is impossible to see what the issue here is. In this case, the `get_offline_config_from_type` function should be raising an explicit exception with a `"Offline store types should end with 'OfflineStore', got {offline_store_type} instead."` message instead of an empty AssertionError. This way it would be immediately clear what the issue was.

### PR DESCRIPTION
**Pull request by tpvasconcelos**
**What this PR does / why we need it**:

This PR adds more explicit error messages to validation checks (for better Pydantic error messages).

Fixes #2696

### CODE REVIEW

**Comment by achals** [comment]
Hey @tpvasconcelos this looks great! One nit is that this should probably be a `fix` or a `chore` instead of a `feat` (the tooling we're using doesn't allow us to cherry pick `feat`s onto patch releases)

**Comment by tpvasconcelos** [comment]
@achals fixed! Let's keep #2696 open for now? I'll try finding some time to take a look at other cases

**Comment by achals** [comment]
Works for me - I'll move it to a draft state so that it doesn't show up on others ppls review dashboard.

**Comment by tpvasconcelos** [comment]
Ah right you want to include everything in a single PR. I'll update the title and description then 👍

**Comment by achals** [comment]
> Ah right you want to include everything in a single PR. I'll update the title and description then 👍

Oh oops! I misunderstood. I am okay merging this in as-is, and keeping the associated ticket open until you feel we have squashed enough of these errors. Please lemme know what you'd like to do!

**Review by adchia — APPROVED** [review]
/lgtm

**Pull request merged**
