### PR TITLE
feat: Add optional private key params to Snowflake config

### PR DESCRIPTION
**Pull request by ArijeetC**
# What this PR does / why we need it:

Adding optional params `private_key` and `private_key_passphrase` to the Snowflake config classes so that they can be used in `feature_store.yaml` file directly.

# Which issue(s) this PR fixes:

Fixes https://github.com/feast-dev/feast/issues/4204

### CODE REVIEW

**Comment by franciscojavierarceo** [comment]
@ArijeetC can you fix the DCO? You can do it in the UI.

**Comment by ArijeetC** [comment]
@franciscojavierarceo fixed it

**Review by franciscojavierarceo — APPROVED** [review]
Lgtm

**Comment by franciscojavierarceo** [comment]
Looks like we have some errors. I think Jeremy is working on this.

**Comment by tokoko** [comment]
Shouldn't these keys be used anywhere? What's the point of adding them?

**Comment by ArijeetC** [comment]
> What's the point of adding them?

@tokoko because it is convenient to have all config defined at a single place (`feature_store.yaml`). Also since these params are optional, I don't think they will cause any problems.

**Comment by tokoko** [comment]
I got that part but the PR is just adding new params, not using them in any way. snowflake connection will be acquired just like before because of [this](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/utils/snowflake/snowflake_utils.py#L72), no?

**Comment by ArijeetC** [comment]
> I got that part but the PR is just adding new params, not using them in any way. snowflake connection will be acquired just like before because of [this](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/utils/snowflake/snowflake_utils.py#L72), no?

Oh, got your question now.

These new params will already be present inside `config_dict` [here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/utils/snowflake/snowflake_utils.py#L68) if they have been defined in the `feature_store.yaml` and they will be added to `kwargs` [here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/utils/snowflake/snowflake_utils.py#L77), that's why no other code change is required.

The `feature_store.yaml` entry I used for testing:
```
offline_store:
    type: snowflake.offline
    user: <...>
    database: <...>
    account: <...>
    private_key: <...>
    private_key_passphrase: <...>
```

**Comment by tokoko** [comment]
@ArijeetC okay, now it's clear. btw, you will have to rebase on master to get rid of it failures.

**Comment by ArijeetC** [comment]
@tokoko done

**Pull request merged**
