### PR TITLE
fix: Add new value types to types.ts for web ui

### PR DESCRIPTION
**Pull request by mirayyuce**
Signed-off-by: Miray Yuce [yucemiray@gmail.com](mailto:yucemiray@gmail.com)

**What this PR does / why we need it**:
Feast web ui parser is failing due to missing value types. Added value types from [https://github.com/feast-dev/feast/blob/master/protos/feast/types/Value.proto](Value.prooto) to [https://github.com/feast-dev/feast/blob/master/ui/src/parsers/types.ts](types.ts)

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by achals** [comment]
@mirayyuce thanks for the contribution! Are all the formatting changes intentional?

**Comment by mirayyuce** [comment]
> @mirayyuce thanks for the contribution! Are all the formatting changes intentional?

Formatting happened when I ran make format-python. Only types.ts was changed intentionally

**Comment by achals** [comment]
> > @mirayyuce thanks for the contribution! Are all the formatting changes intentional?
> 
> Formatting happened when I ran make format-python. Only types.ts was changed intentionally

Okay, the version of the formatter may be different so I pushed a commit with some changes. Change looks good, if you can update the PR to use https://www.conventionalcommits.org/ then that should fix the failling PR title check and should be good to merge!

**Comment by mirayyuce** [comment]
> > > @mirayyuce thanks for the contribution! Are all the formatting changes intentional?
> > 
> > 
> > Formatting happened when I ran make format-python. Only types.ts was changed intentionally
> 
> Okay, the version of the formatter may be different so I pushed a commit with some changes. Change looks good, if you can update the PR to use https://www.conventionalcommits.org/ then that should fix the failling PR title check and should be good to merge!

Thank you so much!

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
