### PR TITLE
feat: Implement spark offline store `offline_write_batch` method

### PR DESCRIPTION
**Pull request by niklasvm**
**What this PR does / why we need it**:

* Create `offline_write_batch` method for spark offline store
* Replace spark testing data sets with a file-based parquet format instead of a temporary view

This PR resolves a further set of failing integration tests.

**Which issue(s) this PR fixes**:

None

### CODE REVIEW

**Comment by achals** [comment]
@niklasvm can you rebase? I think we've fixed the lingering issues with the go unit tests.

**Comment by niklasvm** [comment]
> @niklasvm can you rebase? I think we've fixed the lingering issues with the go unit tests.

Thank you. I've rebased. Waiting for tests now

**Comment by niklasvm** [comment]
@achals looks like tests ran successfully. There are still 2 pending ones. I am not sure if you need to approve before they run

**Review by adchia — APPROVED** [review]
/lgtm

**Pull request merged**
