### PR TITLE
feat: Add health endpoint to py server

### PR DESCRIPTION
**Pull request by robhowley**
Signed-off-by: Rob Howley

**What this PR does / why we need it**:

* add a /health endpoint to python feature server
* it returns 200 and nothing else
* for those not using helm, this is an easy uptime monitoring endpoint

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by robhowley** [comment]
this just looks like a flake, no? seems like it all passed by the code cov upload failed
image
how do i rerun this?

**Review by adchia — APPROVED** [review]
/ok-to-test

**Pull request merged**
