### PR TITLE
Support Alibaba cloud

### PR DESCRIPTION
**Pull request by 777ki**
Add Macompute oflfine store and Hologres online store

### CODE REVIEW

**Comment by adchia** [comment]
Hey! Thanks for the contribution! This is great

With custom connectors, our typical stance is to have a separate Github repo used to implement a plugin (e.g. see https://github.com/baineng/feast-hive for an example). We can then link to the plugin on our repo / website for 3rd party contributions. Feel free to send me PRs in that other repo though and I can comment!

Some noteworthy things about making a separate plugin:
- Re-using the Feast main repo tests needs some work, but @felixwang9817 is looking into this since there are other plugins experiencing the same issue
- Instead of adding a new type of data source to the proto, plugins usually use the "custom source" type (e.g. https://github.com/baineng/feast-hive/blob/main/feast_hive/hive_source.py#L139)

**Comment by adchia** [comment]
friendly ping @777ki on how this was going!

**Comment by 777ki** [comment]
> sorry， some office work make me in trouble，i think i will finish the pull reqeust after chinese new year

**Comment by adchia** [comment]
> > sorry， some office work make me in trouble，i think i will finish the pull reqeust after chinese new year

All good. Let me know if I can help!

**Comment by achals** [comment]
Hi @777ki, are you still planning on working on this PR? Is there anything we can do to help?

**Comment by adchia** [comment]
Closing since the rebase will be really rough. When you get back to this, let's add this to a contrib/ folder like the online store plugins!

**Pull request closed without merging**
