### PR TITLE
feat: Adding DatastoreOnlineStore 'database' argument.

### PR DESCRIPTION
**Pull request by Pawel-Drabczyk**
# What this PR does / why we need it:
When introducing Firestore in Datastore mode in place of Datastore, Google added a possibility to create multiple databases other than (default) (in Datastore there was only one database called (default)). This PR adds 'database' argument to DatastoreOnlineStore. 

# Which issue(s) this PR fixes:

Fixes https://github.com/feast-dev/feast/issues/4113

### CODE REVIEW

**Comment by tokoko** [comment]
@Pawel-Drabczyk you can run `make lint-python` and `make format-python` to fix linter errors

**Comment by Pawel-Drabczyk** [comment]
> @Pawel-Drabczyk you can run `make lint-python` and `make format-python` to fix linter errors

@tokoko, thanks, I did linting and formatting.

**Comment by tokoko** [comment]
@jeremyary Can you do something about tests not starting?

**Comment by jeremyary** [comment]
yep, I did the label, but forgot the "first committer" approve/run, should kick up now

**Review by tokoko — APPROVED** [review]
lgtm

**Review by franciscojavierarceo — APPROVED** [review]
lgtm

**Pull request merged**
