### PR TITLE
chore: Set upper bound for moto package

### PR DESCRIPTION
**Pull request by sudohainguyen**
**What this PR does / why we need it**: `moto` package just recently released version 5.0.0 with some [breaking changes](https://github.com/getmoto/moto/blob/master/CHANGELOG.md), which potentially break our integration tests, so that the upper bound for the package is needed

**Which issue(s) this PR fixes**:

N/A

**Note**: no need to re-compile requirements files since moto is still <5

### CODE REVIEW

**Comment by HaoXuAI** [comment]
Lint failed

**Comment by sudohainguyen** [comment]
> Lint failed

hmm I'm seeing all checks passed

**Comment by HaoXuAI** [comment]
> > Lint failed
> 
> 
> 
> hmm I'm seeing all checks passed

I'm seeing this one failed: https://github.com/feast-dev/feast/actions/runs/7809136271/job/21300448191#step:2:1,
Is it staled?

**Comment by sudohainguyen** [comment]
> > > Lint failed
> > 
> > 
> > hmm I'm seeing all checks passed
> 
> I'm seeing this one failed: https://github.com/feast-dev/feast/actions/runs/7809136271/job/21300448191#step:2:1, Is it staled?

yeah it is staled, already fixed 😄

**Review by HaoXuAI — APPROVED** [review]
lgtm

**Comment by HaoXuAI** [comment]
> > > > Lint failed
> > > 
> > > 
> > > hmm I'm seeing all checks passed
> > 
> > 
> > I'm seeing this one failed: https://github.com/feast-dev/feast/actions/runs/7809136271/job/21300448191#step:2:1, Is it staled?
> 
> yeah it is staled, already fixed 😄

yeah staled on my phone lol

**Pull request merged**
