### PR TITLE
fix: Default to pandas mode if not specified in ODFV proto in database

### PR DESCRIPTION
**Pull request by EXPEbdodla**
# What this PR does / why we need it:
Used pandas mode as default for the ODFV objects that are already present in database. Without this it complaints that mode is missing to convert from Proto to ODFV. 

# Which issue(s) this PR fixes:

# Misc

### CODE REVIEW

**Review by HaoXuAI — APPROVED** [review]
LGTM

**Review by franciscojavierarceo — APPROVED** [review]
Hmm this is defaulted to pandas in the class, did this have issues for you?

**Comment by EXPEbdodla** [comment]
> Hmm this is defaulted to pandas in the class, did this have issues for you?

Defaulted in class if we don't pass it. But from_proto() method we are passing None so it's using None instead of default value of the parameter.

**Comment by franciscojavierarceo** [comment]
Got it, in a follow up PR can you add a test to cover this? I did that in a different PR. Thanks for catching and fixing this!!!

**Comment by EXPEbdodla** [comment]
> Got it, in a follow up PR can you add a test to cover this? I did that in a different PR. Thanks for catching and fixing this!!!

I'll check how I can add this. This is the use case where an ODFV is already registered with old code in Database and the proto doesn't deserialize correctly.

**Pull request merged**
