### PR TITLE
feat: Enabling Datadog in feature server

### PR DESCRIPTION
**Pull request by Akashh17**
**What this PR does / why we need it**:
This PR enables Datadog with feast. Using Datadog's tracing (dtrace) library.

Fixes #

### CODE REVIEW

**Comment by felixwang9817** [comment]
hey @Akashh17 I think you'll need to rebase first - I'm happy to review your PR once you've rebased!

**Review by adchia — APPROVED** [review]
/lgtm

**Review by adchia — APPROVED** [review]
/lgtm

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by adchia** [comment]
A quick note @Akashh17 btw. 

Could you add documentation around this too? (e.g. in https://github.com/feast-dev/feast/blob/master/docs/reference/feature-servers/python-feature-server.md). 

Ideally, this would also be specified as a flag in the helm chart (https://github.com/feast-dev/feast/blob/master/infra/charts/feast-feature-server/README.md)
- Updating the deployment.yaml
- Adding a flag in values.yaml with docs 
- Regenerating the README with `make build-helm-docs`

**Pull request closed without merging**
