### PR TITLE
(WIP) Support Keto authorization directly

### PR DESCRIPTION
**Pull request by khorshuheng**
**What this PR does / why we need it**:
The purpose of this PR is to demonstrate the feasibility of supporting Keto as authorization provider directly without going through feast-keto-auth-server. Further discussion will be needed before deciding whether this feature should be included in Feast or not.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by woop** [comment]
I dont understand why we need this functionality when we already have an auth server implementation that works.

**Comment by khorshuheng** [comment]
> I dont understand why we need this functionality when we already have an auth server implementation that works.

The issue is that, feast auth server would be an additional service to be deployed and maintain. I agree that there are pros and cons between communicating with Keto server directly, or use feast auth server as a middle man. Internally we are still discussing what's the best way to deal with this, hence the WIP progress label.

**Comment by woop** [comment]
> > I dont understand why we need this functionality when we already have an auth server implementation that works.
> 
> The issue is that, feast auth server would be an additional service to be deployed and maintain. I agree that there are pros and cons between communicating with Keto server directly, or use feast auth server as a middle man. Internally we are still discussing what's the best way to deal with this, hence the WIP progress label.

The middleman service is a stateless service that just acts as a proxy. It's as low maintenance as it gets. We cant maintain every implementation for each team. Ultimately we need to allow teams to maintain their own implementations, which is why we created the adapter in the first place.

**Comment by woop** [comment]
Also, you should be targeting https://github.com/feast-dev/feast-java, not the 0.9 branch.

**Comment by woop** [comment]
I'm closing this for now but I am happy to discuss it in our weekly call.

**Pull request closed without merging**
