### PR TITLE
chore: Update snowflake dependencies

### LINKED ISSUE #3237: Allow `snowflake-connector-python >= 2.7.8`
I have a project that uses both `snowpark-python` and `feast`, and this restriction by `feast` on `snowflake-connector-python<=2.7.8` is preventing an upgrade to `snowpark-python==0.10` which now requires `snowflake-connector-python>=2.7.12`.

I would like to know whether this requirement is still valid or whether it can be eased to allow newer versions of `snowflake-connector-python`.

https://github.com/feast-dev/feast/blob/769c31869eb8d9bb693f8a2876cc68b8cdd16521/setup.py#L99

### PR DESCRIPTION
**Pull request by sfc-gh-madkins**
Signed-off-by: miles.adkins <miles.adkins@snowflake.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3237

### CODE REVIEW

**Review by achals — APPROVED** [review]
/lgtm

**Comment by achals** [comment]
You'll have to update the requirements.txt files

**Comment by sfc-gh-madkins** [comment]
@achals running the reqs updates doesnt change anything?

**Pull request merged**
