### PR TITLE
optional include event ts in online feature set

### PR DESCRIPTION
**Pull request by vas28r13**
Signed-off-by: Vitaly Sergeyev <vsergeyev@better.com>

`include_event_ts` optional param to include the event timestamp in the online feature set

This can be useful if the event timestamp impacts logic on the service side of things. 
Can also help evaluate how old the feature vector is.

```
online_response = fs.get_online_features(
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
    ],
    entity_rows=[{"driver_id": 1001}, {"driver_id": 1002}, {"driver_id": 1003}, {"driver_id": 1004}],
    include_event_ts=True,
)

df = online_response.to_df()
df["driver_hourly_stats__ts"]  # should return when the hourly stats were ingested per driver entity
```

### CODE REVIEW

**Comment by adchia** [comment]
You'll need to fix the linter btw. And also add a release note in the description. 

e.g. 

````
```release-note
Allows including event timestamps in online features response
```
````

**Comment by adchia** [comment]
also add to an existing test?

**Comment by woop** [comment]
Just a question here. The point of [FieldStatus](https://github.com/feast-dev/feast/blob/e435d927ecaa2037a6e96cbdf1584e4a15d17597/protos/feast/serving/ServingService.proto#L108) was to provide information about feature values (some of those fields relate to age).
* Is there a reason we'd return the timestamp as part of the feature vector and not a status object or some other metadata object? 
* How would a user replicate the timestamp response on the training side?
* What happens when you have multiple feature views in a single response?

**Comment by vas28r13** [comment]
@woop great questions.
* there is no reason this needs to be part of the fields in the `OnlineResponse`. Like you mentioned, it may be better to have it as separate metadata in the `OnlineReponse` object? I wanted to avoid changing the response object so it felt easiest to have it in the resulting df.
```
online_response = fs.get_online_features(
    features=[
        "driver_hourly_stats:conv_rate",
    ...
    include_event_ts=True,
)

df = online_response.to_df()
df["driver_hourly_stats__ts"]  # should return when the hourly stats were ingested per driver entity
```

* I think this is generally not needed on the training side. I don't necessarily treat this as a feature for the model. There are 2 cases where we use the event timestamps in the ml service:
1. validate that the data is not stale at the time of prediction or track the age of the features at prediction time
2. there is some business logic on the client side based on the age of the features

**Comment by adchia** [comment]
Looks like we started adding this in https://github.com/feast-dev/feast/pull/2166.

Would also be good to think through what the best way to use this as a user of get_online_features (to specifically post process) since the current response python is kind of clunky

**Comment by adchia** [comment]
@tsotnet Assuming you're planning on releasing the new python format soon, so we can probably just not merge this in and migrate to the new response?

**Comment by adchia** [comment]
Created a new issue to track this given the new response: https://github.com/feast-dev/feast/issues/2260

**Pull request closed without merging**
