### PR TITLE
feat: Use ASOF JOIN in Snowflake offline store query

### LINKED ISSUE #4732: Use ASOF JOIN in Snowflake Source
**Is your feature request related to a problem? Please describe.**

Requesting historical features from Snowflake uses multiple intermediate results to do the point-in-time correct join. Recently, a new Snowflake feature was released which does exactly what we would expect from the join: ASOF JOIN (https://www.snowflake.com/en/blog/time-series-analytics-asof-join-generally-available/). The reported improvements in efficiency are very substantial.

**Describe the solution you'd like**

Could we use the ASOF JOIN in https://github.com/feast-dev/feast/blame/d1d80c0d208e25b92047fe5f162c67c00c69bb43/sdk/python/feast/infra/offline_stores/snowflake.py#L717 to improve efficiency of the query? From a superficial view it seems to be possible, only the ttl feature might be difficult with ASOF JOINs.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nanohanno**
# What this PR does / why we need it:

The query template for the Snowflake Offline Store is updated to use the recently added ASOF JOIN (https://www.snowflake.com/en/blog/time-series-analytics-asof-join-generally-available/). We have seen a very substantial improvement in feature queries using the new template. Especially, for large feature tables that have many historical entries for certain entity values the performance is even better than using the `ttl` parameter in the current query template.

# Which issue(s) this PR fixes:

Fixes #4732

# Misc

@bimtauer and @miianiemela have shown interest in the feature, are you able to take a look and test it in your setup?

### CODE REVIEW

**Review by franciscojavierarceo — COMMENTED** [review]
Nice, thank you for this!

**Comment by franciscojavierarceo** [comment]
Looks like integration tests are failing.

**Comment by nanohanno** [comment]
> Looks like integration tests are failing.

I did not realize that there are integation tests for Snowflake, that is great. 
There was a bug in the template for features without entities that we did not check before. Hopefully the fix solves the failing test now.

**Comment by franciscojavierarceo** [comment]
> > Looks like integration tests are failing.
> 
> I did not realize that there are integation tests for Snowflake, that is great. There was a bug in the template for features without entities that we did not check before. Hopefully the fix solves the failing test now.

Hmm. Looks like it's still failing fyi.

**Comment by nanohanno** [comment]
> > > Looks like integration tests are failing.
> > 
> > 
> > I did not realize that there are integation tests for Snowflake, that is great. There was a bug in the template for features without entities that we did not check before. Hopefully the fix solves the failing test now.
> 
> Hmm. Looks like it's still failing fyi.

Yeah, I did not consider setting up the Snowflake integration tests locally and debugging from the CI logs for the template query is a little painful. I have done some improvements today and am still positive that it is close to being there 🙏 . If not I will set up the Snowflake environment in the next days to see the errors in Snowsight.

**Review by franciscojavierarceo — APPROVED** [review]
Thank you for this!

**Pull request merged**
