### PR TITLE
revert: Reverts "fix: Using version args to install the correct feast version"

### PR DESCRIPTION
**Pull request by jeremyary**
Reverts feast-dev/feast#3953

### CODE REVIEW

**Review by franciscojavierarceo — APPROVED** [review]

**Comment by bushwhackr** [comment]
Wouldn't reverting this means that publish workflow `build-wheels/build-docker-image` would test the latest version published in pypi, in this case `0.36.0` and not the release `0.37.0` version? I don't see what is the point of the docker build test then.

I feel that the root problem is that the multicloud Dockerfile pulls from pypi instead of using the `master` branch artifacts which the other Dockerfiles do.

**Comment by jeremyary** [comment]
I feel that the root problem is that the multicloud Dockerfile pulls from pypi instead of using the master branch artifacts which the other Dockerfiles do.

This is correct, however, we'll need to address with a different (or deeper) approach as the fix that was put in place has broken our release process by attempting to force resolution of the PyPi latest/new version without ensuring that the dependency functions correctly. We will be opening an issue shortly to chase the original multicloud image issue after we recover our release process.

**Comment by HaoXuAI** [comment]
> Wouldn't reverting this means that publish workflow `build-wheels/build-docker-image` would test the latest version published in pypi, in this case `0.36.0` and not the release `0.37.0` version? I don't see what is the point of the docker build test then.
> 
> 
> 
> I feel that the root problem is that the multicloud Dockerfile pulls from pypi instead of using the `master` branch artifacts which the other Dockerfiles do.

That's right. Can you point to the other docker file that has the code using master artifacts? I can update to make it work.

In the meantime we need to cut a release which this revert needs

**Comment by bushwhackr** [comment]
Understandable

**Pull request merged**
