### PR TITLE
Fix ValueType.UNIX_TIMESTAMP conversions

### LINKED ISSUE #2209: Serving not working with datetime64 numpy env.
## Expected Behavior 

should work.

## Current Behavior

Serving not working with datetime64 numpy env.
```
  File "/Users/zf/go/src/github.com/opendoor-labs/code/py/.venv/lib/python3.9/site-packages/feast/type_map.py", line 332, in python_values_to_proto_values
    return _python_value_to_proto_value(value_type, values)
  File "/Users/zf/go/src/github.com/opendoor-labs/code/py/.venv/lib/python3.9/site-packages/feast/type_map.py", line 293, in _python_value_to_proto_value
    return [ProtoValue(int64_val=int(value)) for value in values]
  File "/Users/zf/go/src/github.com/opendoor-labs/code/py/.venv/lib/python3.9/site-packages/feast/type_map.py", line 293, in <listcomp>
    return [ProtoValue(int64_val=int(value)) for value in values]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
```
## Steps to reproduce

Serve a feature

### Specifications

- Version:
- Platform:
- Subsystem:

## Possible Solution

Fix: 
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/type_map.py#L292

++ this to type map 
```
            elif isinstance(sample, np.datetime64):
                return [
                ProtoValue(int64_val=int(pd.Timestamp(value).to_pydatetime().timestamp())) for value in values
                ]
```

https://github.com/feast-dev/feast/commit/72bae7d39e3f08df3f98743c412f408924ac3261

### PR DESCRIPTION
**Pull request by judahrand**
Signed-off-by: Judah Rand <17158624+judahrand@users.noreply.github.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2209

**Does this PR introduce a user-facing change?**:

```release-note
Fix ValueType.UNIX_TIMESTAMP conversions
```

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by judahrand** [comment]
> Is there a way to capture this in a test somehow?

Hmmm... 🤔 I guess we just need to add a `ValueType.UNIX_TIMESTAMP` feature to the tests somewhere. I can do this - though in my experience adding new feature types to the tests is a chore 😛

**Comment by judahrand** [comment]
@adchia Added a `datetime` Feature to the tests. Hope this is sufficient.

**Comment by judahrand** [comment]
@adchia Looks likes there's some bugs in the tests that I don't think I'll be able to fix as I don't have access to the AWS or GCP test infrastructure.

**Comment by judahrand** [comment]
@adchia I can only imagine that this method is failing to create the table for Redshift: https://github.com/feast-dev/feast/blob/62fae057d8c36af5f0f302c398f6134fc3c0407d/sdk/python/tests/integration/feature_repos/universal/data_sources/redshift.py#L34

Are you able to help debug this as you have access to the Redshift side?

**Comment by adchia** [comment]
yeah let me take a look

**Comment by judahrand** [comment]
@adchia Did you get a chance to look at this at all? Ideally, I think it makes sense for this and #2229 to go in roughly at the same time as there will be merge conflicts so I'm kinda waiting to review that one until this one can move ahead.

**Comment by adchia** [comment]
I tried it and couldn't repro (i.e. the tests pass for me locally). 

Trying it again now

**Comment by judahrand** [comment]
> I tried it and couldn't repro (i.e. the tests pass for me locally).
> 
> Trying it again now

How odd... Maybe something to do with the credentials on the repo Vs local ones?

I think this is a really important fix as currently I'm not sure `UNIX_TIMESTAMP` features work end to end. Unfortunately, there's not much I can do on my end.

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by felixwang9817** [comment]
cc @judahrand the root cause of the AWS failures on here should be fixed by #2242

**Pull request merged**
