### PR TITLE
Graduate Python feature server

### PR DESCRIPTION
**Pull request by felixwang9817**
**What this PR does / why we need it**: This PR graduates the Python feature server from alpha status by removing the alpha flag check and modifying the docs. It also deletes some useless doc files.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by adchia — COMMENTED** [review]
Think you missed a couple spots. e.g. feature_store.yaml files that have `python_feature_server: true` (there's one in the java serving file + the helm charts at least)

**Comment by felixwang9817** [comment]
@adchia good catch, I think I removed them all

**Comment by pyalex** [comment]
Probably need to fix this as well:
https://github.com/feast-dev/feast/blob/master/java/serving/src/test/resources/docker-compose/feast10/feature_store.yaml

**Review by adchia — APPROVED** [review]
/lgtm

**Pull request merged**
