### PR TITLE
docs: Add import for on_demand_feature_view

### PR DESCRIPTION
**Pull request by KomissarovSemyon**
**What this PR does / why we need it**:
Fix docs for On-demand feature view

**Which issue(s) this PR fixes**:
Missing import for on_demand_feature_view decorator

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by kevjumba** [comment]
Hey @KomissarovSemyon  can you sign your commits? Clicking details on the DCO check should tell you how to do it.

**Comment by felixwang9817** [comment]
hey @KomissarovSemyon quick bump on this - I'm happy to stamp your PR once you [sign your commit](https://docs.feast.dev/project/development-guide#signing-off-commits) in order to pass the DCO check!

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
