### PR TITLE
Fix bug where using some Pandas dtypes in the output of an ODFV fails

### PR DESCRIPTION
**Pull request by judahrand**
**What this PR does / why we need it**:
* When the DataFrame returned by an ODFV UDF uses dtypes like `pd.Int64Dtype()` type mapping fails.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by judahrand** [comment]
Can I have an `ok-to-test` label? I can't run the tests locally so this is the only way I can progress.

**Comment by judahrand** [comment]
This looks good to go to me.

**Review by adchia — APPROVED** [review]
/lgtm

**Pull request merged**
