### PR TITLE
Use LUA script to speed up Redis key retrieval

### PR DESCRIPTION
**Pull request by judahrand**
**What this PR does / why we need it**:
This implements a small (but meaningful for large batch sizes) performance improvement for Redis feature look ups.

I also wonder if it is worth considering how to avoid calling to Redis for each individual FeatureView? At the moment this will add network latency for every FeatureView needed.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
RedisOnlineStore read performance improvement. 
```

### CODE REVIEW

**Comment by pyalex** [comment]
Hey @judahrand , did you run any benchmarks to compare the performance of current master versions vs yours?
What do you understand by large size batch?

**Comment by judahrand** [comment]
> Hey @judahrand , did you run any benchmarks to compare the performance of current master versions vs yours?
> What do you understand by large size batch?

From my local testing it is always faster even for batch size = 1. This is from just using the debugger to get to that point in the code and trying both methods.

**Comment by pyalex** [comment]
By batch size you number of entities?
It doesn't make sense, why this would be faster for single entity

**Comment by judahrand** [comment]
> By batch size you number of entities?
Yes, indeed.

> It doesn't make sense, why this would be faster for single entity
I agree since it is essentially just doing the same thing. The only reason I could think that it might be faster is that there is no overhead of setting up a `pipeline`? Though I'm not sure what that involves on the Redis side.

**Comment by pyalex** [comment]
That's definitely interesting. What amount of features are you requesting per row? What amount is stored in Redis per key?

I've been also working on some latency-related investigation and found out that `hgetall` is 5x faster when amount of requested features is roughly more than 50.

**Comment by pyalex** [comment]
Some quick analysis of Redis + python (redis-py + hiredis):

0. Setup: Redis is populated with maps with 275 fields.
Env:
```
import redis, itertools
r = redis.Redis()
it = r.scan_iter()
keys = list(itertools.islice(it, 0, 100))
fields = list(r.hgetall(keys[0]).keys())
```

Test functions:
```
def test_hmget(keys, fields):
    pipe = r.pipeline()
    for key in keys:
       pipe.hmget(key, fields)
    pipe.execute()
```
```
def test_hgetall(keys):
    pipe = r.pipeline()
    for key in keys:
        pipe.hgetall(key)
    pipe.execute()
```
```
hmget_script = r.register_script("""
    local r = {}
    for _, v in pairs(KEYS) do
    r[#r+1] = redis.call('HMGET', v, unpack(ARGV))
    end
    return r
""")
```
```
hgetall_script = r.register_script("""
    local r = {}
    for _, v in pairs(KEYS) do
    r[#r+1] = redis.call('HGETALL', v)
    end
    return r
""")

Results:

*HMGET in pipeline*
```
%timeit test_hmget(keys[:1], fields[:50])
231 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:1], fields[:100])
430 µs ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:1], fields[:150])
640 µs ± 1.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:1], fields[:200])
898 µs ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:1], fields[:275])
1.34 ms ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:5], fields[:50])
781 µs ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:10], fields[:50])
1.37 ms ± 5.03 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hmget(keys[:20], fields[:50])
2.57 ms ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:30], fields[:50])
3.7 ms ± 25.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:40], fields[:50])
4.88 ms ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:50], fields[:50])
6.1 ms ± 56.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:50], fields[:100])
14.3 ms ± 406 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:100], fields[:50])
11.9 ms ± 79.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hmget(keys[:100], fields[:100])
27.7 ms ± 212 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit test_hmget(keys[:100], fields[:150])
49.2 ms ± 4.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit test_hmget(keys[:100], fields[:200])
70.4 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit test_hmget(keys[:100], fields[:275])
115 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

*HGETALL in pipeline*
```
%timeit test_hgetall(keys[:1])
589 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hgetall(keys[:10])
1.34 ms ± 26.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hgetall(keys[:5])
742 µs ± 4.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit test_hgetall(keys[:20])
2.52 ms ± 38.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hgetall(keys[:30])
3.62 ms ± 20 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hgetall(keys[:40])
4.81 ms ± 26.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hgetall(keys[:50])
6.02 ms ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hgetall(keys[:100])
11.9 ms ± 92.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

*HMGET in script*
```
%timeit hmget_script(keys[:1], fields[:50])
236 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:1], fields[:100])
481 µs ± 4.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:1], fields[:150])
718 µs ± 2.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:1], fields[:200])
977 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:1], fields[:275])
1.62 ms ± 47.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:5], fields[:50])
533 µs ± 44.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:10], fields[:50])
800 µs ± 2.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:20], fields[:50])
1.35 ms ± 9.73 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:30], fields[:50])
1.83 ms ± 23.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hmget_script(keys[:40], fields[:50])
2.35 ms ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hmget_script(keys[:50], fields[:50])
2.91 ms ± 71.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hmget_script(keys[:100], fields[:50])
5.46 ms ± 29 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hmget_script(keys[:100], fields[:100])
14.9 ms ± 68.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hmget_script(keys[:100], fields[:150])
29.8 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit hmget_script(keys[:100], fields[:200])
47.6 ms ± 487 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit hmget_script(keys[:100], fields[:275])
82.4 ms ± 450 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

*HGETALL in script*
```
%timeit hgetall_script(keys[:1])
273 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hgetall_script(keys[:5])
1.11 ms ± 3.17 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hgetall_script(keys[:10])
1.91 ms ± 5.49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit hgetall_script(keys[:20])
4.02 ms ± 29.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hgetall_script(keys[:30])
5.88 ms ± 30.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hgetall_script(keys[:40])
7.77 ms ± 58 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hgetall_script(keys[:50])
9.63 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit hgetall_script(keys[:100])
18.7 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit test_hgetall(keys[:100])
10.6 ms ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by pyalex** [comment]
From my results - the script is not faster than hmget on a single key (which totally makes sense to me). However, it gives a really good boost when the number of keys (rows) is increased. 
HGETALL wins with an increasing number of fields. Roughly after 50 fields - it becomes faster than hmget script. And scripting doesn't help with hgetall, because (my theory) parsing overhead (of arbitrary output) prevails the benefit of a single command.

**Comment by pyalex** [comment]
But even though there's a benefit from using script inside Redis - it's not directly supported by Redis Cluster client, which can send the command to only a single node. And thus merging this will break our support of Redis Cluster.

**Comment by judahrand** [comment]
> But even though there's a benefit from using script inside Redis - it's not directly supported by Redis Cluster client, which can send the command to only a single node. And thus merging this will break our support of Redis Cluster.
> 
> That being said, I think we still can implement our own router for cluster support, but it would be a little trickier.

Ah - this is a good point... I believe it might be possible to make it work somehow with hash tags but that does sound like too much work! I suppose I shall close this for now?

**Pull request closed without merging**
