### PR TITLE
fix: Added generic Feature store Creation for CLI

### PR DESCRIPTION
**Pull request by nj7**
**What this PR does / why we need it**:
This PR creates generic functionality to create a Feature store for the CLI command to have the same functionality across commands.

Currently only serve uses ENV variable-based config loader using the same functionality across commands.

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by adchia** [comment]
Would you mind signing your commit?

**Comment by nj7** [comment]
added a sign commit and corrected lint/formatting issue

**Comment by nj7** [comment]
@adchia can you please merge it. I am not having privileges to do

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Comment by felixwang9817** [comment]
@nj7 this has been merged!

**Pull request merged**
