### PR TITLE
fix: Change numpy version on setup.py and upgrade it to resolve dependabot warning

### PR DESCRIPTION
**Pull request by breno-costa**
**What this PR does / why we need it**:
Dependabot cannot update numpy to a non-vulnerable version because the numpy version is pinned on setup.py, and it looks like numpy version was wrongly pinned by a recent change introduced on PR https://github.com/feast-dev/feast/pull/2647

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by achals — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by achals** [comment]
Thanks for the fix @breno-costa !

**Comment by breno-costa** [comment]
@achals I've checked the test `java_pr / integration-test` that failed on my first commit.

That integration test was building a docker image using the base image [python:3.7](https://github.com/feast-dev/feast/blob/master/java/serving/src/test/resources/docker-compose/feast10/Dockerfile#L1). It installs requirements from the [requirements.txt](https://github.com/feast-dev/feast/blob/master/java/serving/src/test/resources/docker-compose/feast10/Dockerfile#L1) and installs Feast dependencies on [entrypoint](https://github.com/feast-dev/feast/blob/master/java/serving/src/test/resources/docker-compose/feast10/entrypoint.sh#L7) during the test execution. The [github action log](https://pipelines.actions.githubusercontent.com/serviceHosts/ccc6f570-b2e5-4ff0-a224-fc17f6553095/_apis/pipelines/1/runs/41952/signedlogcontent/21?urlExpires=2022-06-29T21%3A50%3A57.7638452Z&urlSigningMethod=HMACV1&urlSignature=CexReDvTRKT0JXKBwgjNY7PnZnALBL3prMp%2FeCsoN94%3D) shows it can only install `numpy-1.21.6` after dependency resolution - but my PR is upgrading numpy to `1.22.0`.

According to [numpy release notes](https://numpy.org/devdocs/release/1.22.0-notes.html), python 3.7 is not supported by numpy from `1.22.0`.

> The Python versions supported in this release are 3.8-3.10, Python 3.7 has been dropped.

To fix that integration test, I'm also changing the dockerfile to upgrade python base image from 3.7 to 3.8. Let me know if you have any concern about this change or if we can proceed to merge the branch.

**Comment by achals** [comment]
@breno-costa nope, upgrading to python 3.8 for the dockerfile is fine by me. 

/lgtm

**Pull request merged**
