### PR TITLE
fix: Integration tests for async sdk method

### PR DESCRIPTION
**Pull request by breno-costa**
# What this PR does / why we need it:
Follow up on https://github.com/feast-dev/feast/pull/4172 After checking integration tests, I understand this one is relevant to the async method. Let me know if you understand more integration tests are needed.

# Which issue(s) this PR fixes:

# Fixes

### CODE REVIEW

**Comment by tokoko** [comment]
I wonder it there's a way to do this without introducing another test. We could eventually use `@pytest.mark.parametrize("use_async_client", [True, False], ids=lambda v: str(v))` on existing tests, but not sure how would we be able to right now limit async tests to only redis (without also limiting sync ones).

**Comment by breno-costa** [comment]
> I wonder it there's a way to do this without introducing another test. We could eventually use `@pytest.mark.parametrize("use_async_client", [True, False], ids=lambda v: str(v))` on existing tests, but not sure how would we be able to right now limit async tests to only redis (without also limiting sync ones).

I'm not sure whether it's possible to configure tests in this way. I refactored a little bit to reuse same setup and assertions for both sync and async sdk methods. This may help. wdyt?

**Comment by tokoko** [comment]
thanks, this looks a lot better.

**Review by tokoko — APPROVED** [review]
lgtm

**Comment by tokoko** [comment]
@breno-costa Can you take a look here? you can ignore `test_historical_features` fails, but others seem legit.

**Comment by breno-costa** [comment]
> @breno-costa Can you take a look here? you can ignore `test_historical_features` fails, but others seem legit.

Fixed the issue. 
Would it be possible to run integration tests locally?

**Comment by tokoko** [comment]
@breno-costa thanks. There's a `test-python-integration-local` command in Makefile, It's used to run integration tests except for the ones that depend on AWS/GCP accounts.

**Review by franciscojavierarceo — APPROVED** [review]

**Pull request merged**
