### PR TITLE
fix: Fix materialization when running on Spark cluster.

### PR DESCRIPTION
**Pull request by ckarwicki**
**What this PR does / why we need it**:
When running materialization and have Spark offline store configured to use cluster (`spark.master` pointing to actual Spark master node) `self.to_spark_df().write.parquet(temp_dir, mode="overwrite")` will create parquet file in worker node but `return pq.read_table(temp_dir)` is executed on driver node and it can't read from worker. Proposed fix makes materialization work when run on Spark cluster.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by achals** [comment]
Thanks for the PR @ckarwicki , have you been able to test this out yourself?

**Comment by ckarwicki** [comment]
@achals Yes, this has been tested on Spark cluster.

**Comment by adchia** [comment]
Hey! @ckarwicki can you also sign your commits?

**Review by adchia — APPROVED** [review]

**Comment by niklasvm** [comment]
This may break some of the unit tests that test for data types being preserved between arrow and spark. I previously changed [this](https://github.com/feast-dev/feast/commit/b26566d92573164d9968fb356fd68446725f70f5) method to resolve failing unit tests.

**Comment by kevjumba** [comment]
@ckarwicki can you sign your commits, the DCO check details should give you a command to sign them

**Comment by ckarwicki** [comment]
@kevjumba signed commits.

**Review by kevjumba — APPROVED** [review]
/lgtm

**Pull request merged**
