### PR TITLE
Remove feature set update from job update cycle

### LINKED ISSUE #664: Job Management Optimizations
Creating this card to track opportunities to optimize the existing Job Managers and related code. Some of these have been identified from previous PRs like #650. 

* [Reduce the amount of DB lookups per poll](https://github.com/gojek/feast/pull/650#discussion_r417447673)
* [Reduce the amount of rows returned from jobRepository](https://github.com/gojek/feast/pull/650#discussion_r417447673)
* Possibly remove `updateFeatureSetStatuses` if the status can be found by looking at job state.
* [Optimize feature set retrieval in JobCoordinator](https://github.com/gojek/feast/pull/655#discussion_r418469266)

### PR DESCRIPTION
**Pull request by zhilingc**
**What this PR does / why we need it**:
Removes the feature set update from the job update cycle, because job updates are long running and are write-transactional, and so can block feast core for long periods of time. Hopefully this improves the performance of the system.

The responsibility of making feature set status updates is pushed to when the feature set is retrieved (either by ListFeatureSets or GetFeatureSet). 

Would like the dataflow tests to be fixed and run on this PR before this is merged in, ideally. 

**Which issue(s) this PR fixes**:

Fixes #664

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zhilingc** [comment]
PR is broken after rebase 😿

**Comment by woop** [comment]
Let's pick this up in the future if its necessary. Made somewhat redundant by #792.

**Pull request closed without merging**
