### PR TITLE
docs: Document DynamoDBOnlineStore public methods

### LINKED ISSUE #2346: [Docs] Explain DynamoDB online_write_batch uses a batch_writer
## Expected Behavior 

`DynamoDBOnlineStore` method `online_write_batch` uses a [BatchWriter](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#batch-writing) under the hood. 

User documentation should explain the advantages of using it, including 

> automatically handle buffering and sending items in batches. In addition, the batch writer will also automatically handle any unprocessed items and resend them as needed.

### PR DESCRIPTION
**Pull request by TremaMiguel**
**What this PR does / why we need it**:

 User using a `DynamoDBOnlineStore` should be aware that he/she can load a lot of data at a time without worrying about it, because the implementation uses [BatchWriter](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#batch-writing) under the hood. 

**Which issue(s) this PR fixes**:

Fixes #2346 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by felixwang9817** [comment]
@TremaMiguel thanks for the PR! couple quick notes:
1. you'll need to sign your commits to pass the DCO check; see [here](https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md#signing-off-commits) for more details
2. you'll need to pass the lint + format checks; you can run these with `make lint-python` and `make format-python`; you can see more details [here](https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md#pre-commit-hooks)

**Comment by TremaMiguel** [comment]
@felixwang9817 is it possible that DCO checks fails for `unknown` name, previous force push commits were signed off with unknown name and DCO passed.

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Comment by woop** [comment]
Thanks @TremaMiguel!!

**Pull request merged**
