### PR TITLE
Broaden google-cloud-core dependency

### PR DESCRIPTION
**Pull request by ptoman-pa**
**What this PR does / why we need it**:
Broadens dependency on google-cloud-core. The limitation to 1.4.* seems tighter than it needs to be. The version 1.7.2 (which is the latest before 2.0.0) passes unit tests and makes feast more interoperable as a library with other systems.

**Which issue(s) this PR fixes**:
Relates to https://github.com/feast-dev/feast/issues/928

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ptoman-pa** [comment]
@felixwang9817 Thank you for the polite reminder! Signed.

**Comment by felixwang9817** [comment]
hey @ptoman-pa, I don't think the signing worked properly. if you look at your [commit](https://github.com/feast-dev/feast/pull/2094/commits/2c36e3b8cdad8d49b587712e98517d3360327fd2), you'll see it doesn't have the "signed off by" note that other [commits](https://github.com/feast-dev/feast/pull/2099/commits/c4736dc944401bec113a358c51cb9bef109e78c3) have - could you try signing again with `git commit -s`? thanks!

**Comment by ptoman-pa** [comment]
Done. Also added a note about the project wanting signoffs rather than GPG, but we can remove that or break it into a separate PR depending on your preferences for repo management.

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Comment by felixwang9817** [comment]
thanks for adding that note to our docs @ptoman-pa! it looks like the first of two commits is signed off properly, but the second isn't - would you mind fixing that? apologies for all the back and forth!

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
