### PR TITLE
fix: Specifies timeout in exception polling

### PR DESCRIPTION
**Pull request by gbmarc1**
**What this PR does / why we need it**:
google-api-core==2.11.0 change the default value for polling the exception as per ->
https://github.com/googleapis/python-api-core/issues/479

`block_until_done` funciton would failt because of a TypeError

This is a quick patch to support google-api-core 2.11.0

### CODE REVIEW

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Comment by felixwang9817** [comment]
@gbmarc1 this PR lgtm, you'll have to [sign](https://docs.feast.dev/project/development-guide#signing-off-commits) your commit for the DCO check to pass!

**Comment by gbmarc1** [comment]
> @gbmarc1 this PR lgtm, you'll have to [sign](https://docs.feast.dev/project/development-guide#signing-off-commits) your commit for the DCO check to pass!

Done

**Pull request merged**
