### PR TITLE
chore: Rename Helm Operator

### PR DESCRIPTION
**Pull request by tchughesiv**
# What this PR does / why we need it:
This PR is to more clearly define that the existing feast operator is actually a Helm-based operator. This is important as we are likely to introduce a new Go-based operator in the near future. 
Prerequisite to https://github.com/feast-dev/feast/issues/4561

# Misc
@franciscojavierarceo Before we merge this PR, we'll require a new docker repo named "feast-helm-operator". It should replicate the permissions of the existing feast-operator repo below. The new Go-based operator would use the existing "feast-operator" repo going forward. We'll make a swap.
https://hub.docker.com/r/feastdev/feast-operator

### CODE REVIEW

**Review by franciscojavierarceo — APPROVED** [review]
lgtm

**Comment by franciscojavierarceo** [comment]
Should we use this as an opportunity to migrate to quay instead?

**Comment by tchughesiv** [comment]
imo, the move to quay.io should start with our pre-release GCR images @ gcr.io/kf-feast. the docker.io images are our "release" images and probably shouldn't be the first to go.

**Review by franciscojavierarceo — APPROVED** [review]
approved

**Pull request merged**
