### PR TITLE
chore: Support pandas 2

### LINKED ISSUE #3709: Pandas 2.0 support
**Is your feature request related to a problem? Please describe.**

I'm trying to install feast with pandas 2.0.3, but feast is pinned to pandas `<2`: https://github.com/feast-dev/feast/blob/c75a01fce2d52cd18479ace748b8eb2e6c81c988/setup.py#L55

**Describe the solution you'd like**

Allow pandas >2. I'm not sure how much effort it will be, my experience upgrading has been simple, and provided there's a good test coverage of the pandas features being used by feast, it should be fine.

**Describe alternatives you've considered**

I could rollback my codebase to an older version of pandas but I'm using some of the new feature and rely on recent bug fixes.

**Additional context**

```
python3.9 -m venv --clear tmp
source tmp/bin/activate/
pip install pandas==2.0.3 feast==0.31.1

ERROR: Cannot install feast==0.31.1 and pandas==2.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pandas==2.0.3
    feast 0.31.1 depends on pandas<2 and >=1.4.3


```

### PR DESCRIPTION
**Pull request by sudohainguyen**
**What this PR does / why we need it**:
Relax pandas upper bound to support v2.0

**Which issue(s) this PR fixes**: 

Fixes #3709 

**Additional changes**:

Set upper bound for moto due to its recent breaking changes in [5.0.0](https://github.com/getmoto/moto/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by sudohainguyen** [comment]
pending on #3925
cc: @franciscojavierarceo

**Comment by sudohainguyen** [comment]
seems the issue appears in integration tests related to this issue from pandas https://github.com/pandas-dev/pandas/issues/55730

we need to pin pandas version to at least 2.1.3 in order to adopt pandas v2, however the library only supports python 3.8 till 2.0.3

**Review by HaoXuAI — APPROVED** [review]
nicee!

**Comment by sudohainguyen** [comment]
still err, hang on, working on it

**Pull request closed without merging**
