### PR TITLE
chore: Add Daniele and Lokesh as Approvers and Reviewers

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
# What this PR does / why we need it:
Add Daniele and Lokesh as Approvers and Reviewers

# Which issue(s) this PR fixes:
N/A

# Misc

### CODE REVIEW

**Comment by tokoko** [comment]
This is not gonna work unfortunately, OWNERS file is supposed to be read by [prow](https://docs.prow.k8s.io/docs/overview/), which I'm pretty sure is not longer active, not sure who was hosting it in the first place.

**Comment by tokoko** [comment]
just making sure.. CODEOWNERS just means the group will be requested a review if a PR touches any of those folders. It doesn't actually give any new permissions to either approve or merge.

**Comment by franciscojavierarceo** [comment]
I have that configured in the repo settings.

Screenshot 2024-10-23 at 12 31 57 PM

**Comment by franciscojavierarceo** [comment]
Nope! There's configuration to do round robin and only requiring one approver.

**Comment by franciscojavierarceo** [comment]
You only need one approver before merging.

**Comment by franciscojavierarceo** [comment]
can you approve? :D

**Review by tokoko — APPROVED** [review]

**Pull request merged**
