### PR TITLE
ci: Fix setuptools issue with wildcard

### PR DESCRIPTION
**Pull request by adchia**
**What this PR does / why we need it**:
Converts dependencies to use ~= or explicit versions since wildcard versions don't seem to be working with setuptools

One issue that came up was mypy-protobuf had to be pinned to an older version to overcome some lint issues around stubs not successfully installing

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by gbmarc1 — APPROVED** [review]
LGTM

**Comment by achals** [comment]
Ugh that's annoying. did this change with specific versions of pip or something else?

**Pull request merged**
