### PR TITLE
docs: Add ScyllaDB as online store alternative

### PR DESCRIPTION
**Pull request by zseta**
**What this PR does / why we need it**:

Add documentation about ScyllaDB and ScyllaDB Cloud as online store alternatives. ScyllaDB can use the already existing Cassandra connector.

### CODE REVIEW

**Comment by HaoXuAI** [comment]
@zseta Could you please pass the DCO? It's a good work👍

**Comment by zseta** [comment]
@HaoXuAI Done (I hope I did it correctly).

**Comment by jeremyary** [comment]
Hey @zseta unfortunately it seems to me that the commit's still failing DCO. More details identifying the commit & steps can be found [here](https://github.com/feast-dev/feast/pull/3656/checks). Once resolved, we should see sign-off info on the commit similar to this screenshot from a random recent merged commit [here](https://github.com/feast-dev/feast/pull/3938/commits/b9b8b26be229c4225be0edec2a89681d0247612a) (just as an example)
image

**Comment by zseta** [comment]
Any chance I can just open a new PR with the same changes? I'm having issues with DCO so it would be easier..🙏

**Comment by jeremyary** [comment]
> Any chance I can just open a new PR with the same changes? I'm having issues with DCO so it would be easier..🙏

Seems ok to me, I've been known to do similar when I distrust my local repo state :) any considerations I'm overlooking that come to mind @HaoXuAI ?

**Comment by HaoXuAI** [comment]
> > Any chance I can just open a new PR with the same changes? I'm having issues with DCO so it would be easier..🙏
> 
> Seems ok to me, I've been known to do similar when I distrust my local repo state :) any considerations I'm overlooking that come to mind @HaoXuAI ?

nope, definitely not a concern. go ahead to open another one

**Comment by zseta** [comment]
Opened a [new PR](https://github.com/feast-dev/feast/pull/3944) with proper DCO

**Pull request closed without merging**
