### PR TITLE
chore: Unpin `googleapis-common-protos`

### PR DESCRIPTION
**Pull request by chhabrakadabra**
**What this PR does / why we need it**:

Exact pinning this library can cause Feast to be incompatible with other libraries that users may want to install.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by achals** [comment]
You'll probably need to regenerate the requirements files!

**Comment by chhabrakadabra** [comment]
I had some trouble with generating the requirements files and I would really appreciate it if someone could double-check my work. 

For one, the make targets `lock-python-dependencies` and `lock-python-ci-dependencies` work differently from the commands right at the top (in the comments) in the requirements files and produce very different results. For example, the command `PYTHON=3.7 make lock-python-ci-dependencies` fails to generate the 3.7 CI requirements file, but the command at the top of that file `pip-compile --output-file=sdk/python/requirements/py3.7-requirements.txt` succeeds.

Another issue is why that make target mentioned above fails. It fails with the following error:

```
(.venv37) abhin@Abhins-personal-MB feast % PYTHON=3.7 make lock-python-ci-dependencies                             
python -m piptools compile -U --extra ci --output-file sdk/python/requirements/py3.7-ci-requirements.txt
ERROR:pep517.envbuild:ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ERROR:pep517.envbuild:sphinx-rtd-theme 1.0.0 requires docutils<0.18, but you have docutils 0.18.1 which is incompatible.
ERROR:pep517.envbuild:great-expectations 0.14.13 requires jinja2<3.1.0,>=2.10, but you have jinja2 3.1.2 which is incompatible.
ERROR:pep517.envbuild:great-expectations 0.14.13 requires pyparsing<3,>=2.4, but you have pyparsing 3.0.9 which is incompatible.
ERROR:pep517.envbuild:flake8 4.0.1 requires importlib-metadata<4.3; python_version < "3.8", but you have importlib-metadata 4.11.4 which is incompatible.
ERROR:pep517.envbuild:feast 0.21.1.dev31+g46006d2e.d20220531 requires protobuf<3.20,>=3.10, but you have protobuf 3.20.1 which is incompatible.
ERROR:pep517.envbuild:WARNING: You are using pip version 22.0; however, version 22.1.2 is available.
ERROR:pep517.envbuild:You should consider upgrading via the '/Users/abhin/src/github.com/chhabrakadabra/feast/.venv37/bin/python -m pip install --upgrade pip' command.
ERROR:pep517.envbuild:ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ERROR:pep517.envbuild:sphinx-rtd-theme 1.0.0 requires docutils<0.18, but you have docutils 0.18.1 which is incompatible.
ERROR:pep517.envbuild:great-expectations 0.14.13 requires jinja2<3.1.0,>=2.10, but you have jinja2 3.1.2 which is incompatible.
ERROR:pep517.envbuild:great-expectations 0.14.13 requires pyparsing<3,>=2.4, but you have pyparsing 3.0.9 which is incompatible.
ERROR:pep517.envbuild:flake8 4.0.1 requires importlib-metadata<4.3; python_version < "3.8", but you have importlib-metadata 4.11.4 which is incompatible.
ERROR:pep517.envbuild:feast 0.21.1.dev31+g46006d2e.d20220531 requires protobuf<3.20,>=3.10, but you have protobuf 3.20.1 which is incompatible.
ERROR:pep517.envbuild:WARNING: You are using pip version 22.0; however, version 22.1.2 is available.
ERROR:pep517.envbuild:You should consider upgrading via the '/Users/abhin/src/github.com/chhabrakadabra/feast/.venv37/bin/python -m pip install --upgrade pip' command.
Could not find a version that matches cryptography<37.0.0,==3.4.8,>=2.1.4,>=2.5,>=3.1.0,>=3.2,>=3.3.1,>=35.0 from https://files.pythonhosted.org/packages/00/e4/da1509e64a92e32ec8df97f5c4372e7f0e56b5b0bad299da61a9632b900c/cryptography-3.4.8-cp36-abi3-macosx_10_10_x86_64.whl#sha256=a00cf305f07b26c351d8d4e1af84ad7501eca8a342dedf24a7acb0e7b7406e14 (from feast (setup.py))
Tried: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2, 2.2.1, 2.2.1, 2.2.2, 2.2.2, 2.3, 2.3, 2.3.1, 2.3.1, 2.4, 2.4, 2.4.1, 2.4.1, 2.4.2, 2.4.2, 2.5, 2.5, 2.6, 2.6.1, 2.6.1, 2.7, 2.7, 2.8, 2.8, 2.9, 2.9, 2.9.1, 2.9.1, 2.9.2, 2.9.2, 3.0, 3.0, 3.1, 3.1, 3.1.1, 3.1.1, 3.2, 3.2, 3.2.1, 3.2.1, 3.3, 3.3, 3.3.1, 3.3.1, 3.3.2, 3.3.2, 3.4, 3.4, 3.4, 3.4.1, 3.4.1, 3.4.2, 3.4.2, 3.4.3, 3.4.3, 3.4.4, 3.4.4, 3.4.5, 3.4.5, 3.4.6, 3.4.6, 3.4.7, 3.4.7, 3.4.8, 3.4.8, 35.0.0, 35.0.0, 36.0.0, 36.0.0, 36.0.0, 36.0.1, 36.0.1, 36.0.1, 36.0.2, 36.0.2, 36.0.2, 37.0.0, 37.0.0, 37.0.0, 37.0.1, 37.0.1, 37.0.1, 37.0.2, 37.0.2, 37.0.2
There are incompatible versions in the resolved dependencies:
  cryptography==3.4.8 from https://files.pythonhosted.org/packages/00/e4/da1509e64a92e32ec8df97f5c4372e7f0e56b5b0bad299da61a9632b900c/cryptography-3.4.8-cp36-abi3-macosx_10_10_x86_64.whl#sha256=a00cf305f07b26c351d8d4e1af84ad7501eca8a342dedf24a7acb0e7b7406e14 (from feast (setup.py))
  cryptography<37.0.0,>=3.1.0 (from snowflake-connector-python[pandas]==2.7.8->feast (setup.py))
  cryptography>=2.1.4 (from azure-storage-blob==12.12.0->adlfs==0.5.9->feast (setup.py))
  cryptography>=3.2 (from great-expectations==0.14.13->feast (setup.py))
  cryptography>=3.3.1 (from moto==3.1.11->feast (setup.py))
  cryptography>=2.5 (from azure-identity==1.10.0->adlfs==0.5.9->feast (setup.py))
  cryptography>=35.0 (from pyOpenSSL==22.0.0->snowflake-connector-python[pandas]==2.7.8->feast (setup.py))
make: *** [lock-python-ci-dependencies] Error 2
```

As far as I can tell, that error is legitimate. We legitimately pin `cryptography` to `3.4.8`, which seems incompatible with the `snowflake-connector-python[pandas]` requirement of `>=35.0`. So what actually surprises me is not that this command fails, but why the other command even succeeds. I'm not 100% sure how this has ever worked in the past. I'd appreciate any help and guidance on this. Thanks.

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by casassg** [comment]
Hey folks, any chance to do a patch release with this unpinning? Made super difficult to figure out why this failed: https://github.com/tensorflow/tfx-addons/pull/152

**Comment by adchia** [comment]
kicking off! sorry about that!

**Comment by adchia** [comment]
Release is out!

**Pull request merged**
