### PR TITLE
Fix FeatureSetJobStatus removal

### PR DESCRIPTION
**Pull request by pyalex**
**What this PR does / why we need it**:

Currently due to cascade relations from both Job and FeatureSet to FeatureSetJobStatus it's impossible to delete FeatureSetJobStatus. As a solution I propose to delete cascade on FeatureSet side because:
1. We manage FeatureSetJobStatus from Job side
2. Ideally when we completely decouple JobCoordination from Core there will be no foreign key (relationship in general) to FeatureSet in FeatureSetJobStatus (see my other PR #852 )
3. Currently we not planning to physically delete feature sets. Even if we will delete them - only by marking as deleted.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mrzzy** [comment]
Its not clear what this problem this solves. @pyalex mind updating PR description?

**Comment by pyalex** [comment]
@mrzzy updated PR description

**Comment by woop** [comment]
Ok makes sense. Deletion is hard. It will cause inconsistency here. Lets assume feature sets dont get deleted completely but only marked as deleted.

**Pull request merged**
