### PR TITLE
fix: Resolve small typo in README file

### PR DESCRIPTION
**Pull request by sudohainguyen**
**What this PR does / why we need it**: to beautify README document on github view.

**Which issue(s) this PR fixes**: simply add a space between brackets

### CODE REVIEW

**Comment by kevjumba** [comment]
@sudohainguyen Please resolve the DCO errors, if you click the details, it'll give you a command to run to resolve them!

**Review by kevjumba — APPROVED** [review]
/lgtm

**Comment by kevjumba** [comment]
@sudohainguyen please rebase to fix the local integration

**Comment by sudohainguyen** [comment]
thanks a lot @kevjumba. Hope this time works

**Pull request merged**
