### PR TITLE
chore: Use pixi to lock python dependencies in a single command

### PR DESCRIPTION
**Pull request by tokoko**
# What this PR does / why we need it:
Adds `lock-python-dependencies-all` command in Makefile, that uses [pixi](https://prefix.dev/) (basically a faster alternative to conda) to regenerate all requirements files in a single command. I haven't changed the way dependencies are compiled yet, pixi is only used to provide a python runtime of a different version.

### CODE REVIEW

**Comment by sudohainguyen** [comment]
how does it compare to poetry? 🤔

**Comment by tokoko** [comment]
@sudohainguyen Well.. generally, poetry does a lot more, pixi is just a faster conda with better interface. If we are talking about environment management part, pixi and conda are more universal package managers, so they can manage python runtime itself as well, poetry manages only pypi packages with a python runtime that needs to be in-place.

**Comment by sudohainguyen** [comment]
I see, just wondering that is there a success example of other opensource projects using pixi? 

another point, it would be great if we can integrate `uv` for packages resolver as well

**Comment by tokoko** [comment]
Not sure about pixi adoption tbh, haven't really come across anywhere else, but I think the use case in this PR is not critical enough to warrant that. uv probably has better adoption, i think airflow is using it already. pixi does use `uv` under the hood for python packages btw and the projects are sort of intertwined generally.

Did you have time to look at this #4086? That PR only changes install step without touching resolver. I tried resolving locally as well, it was a lot faster, it just generated requirements files that were slightly different from current ones in formatting so I put it off for a little bit. Definitely worth making the change though.

**Review by jeremyary — APPROVED** [review]

**Pull request merged**
