### PR TITLE
Farfetch fork from 0.7 to support databricks integration

### PR DESCRIPTION
**Pull request by rafalzydowicz**
**What this PR does / why we need it**:

This PR adds support for databricks integration.  On the server side, this means a new DatabricksJobManager.  There have been minor changes to some common classes and extraction of some others to common modules to avoid unwanted beam dependencies leaking into our Spark jars.  Otherwise, most changes are contained under spark and databricks folders.  On the python client side, we have added support for azure data lake storage for the staging location.  It requires a AZURE_CLIENT_ID, AZURE_TENANT_ID, and AZURE_CLIENT_SECRET.  We are in the process of implementing device code flows for a few future release.

There is also a databricks emulator, or facade really, which provides a databricks API layer and runs Spark locally.  It's not currently being used in our testing.

Ingestion metric naming conventions along with tags have been retained, with slightly altered prefixes on account of Spark source names and executor identifiers.  We continued to use the original StatsdReporter and massaged the naming to allow tags to be included.  Only Inflight and Deadletter metrics are currently implemented.

We are aware that v0.8 has a new Spark implementation, which is why we are merging this against v0.7.

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

No API changes

```release-note

```

### CODE REVIEW

**Comment by woop** [comment]
@rafalzydowicz are you still actively working on this rebase?

**Comment by rafalzydowicz** [comment]
> @rafalzydowicz are you still actively working on this rebase?

Yes, we are developing against it on our fork, but this PR is ready.  The integration tests are failing, but they are failing on the v7 branch in general (unless I'm missing something) and the jupyter build push because the image isn't found.  Would you want these all fixed on this branch?

As an aside, considering your active development of spark on master, what is our goal with this PR?

**Comment by woop** [comment]
> > @rafalzydowicz are you still actively working on this rebase?
> 
> Yes, we are developing against it on our fork, but this PR is ready. The integration tests are failing, but they are failing on the v7 branch in general (unless I'm missing something) and the jupyter build push because the image isn't found. Would you want these all fixed on this branch?

Ok, well we will need to fix the tests then. Will keep it open for the time being.

> As an aside, considering your active development of spark on master, what is our goal with this PR?

Two reasons to get this merged in.
1. It will take a while for 0.7 users to move to the 0.8+ architecture since its fundamentally different, so it makes sense to keep developing on 0.7 for now.
2. The databricks specific functionality that you have here, especially around Delta and SparkSQL, will be useful for the development we will do in 0.9 (when we try and add Delta support). At the start that will be open source only, but we will probably add databricks API support later. You've already done most of the heavy lifting to add that support, even if we dont use the code verbatim.

**Comment by rafalzydowicz** [comment]
@woop, docker build is still failing because it can't find images on docker.io.  This may be related to a bug with buildkit mentioned at the bottom of https://docs.docker.com/develop/develop-images/build_enhancements/.  Can you please have a look?

**Comment by woop** [comment]
> @woop, docker build is still failing because it can't find images on docker.io. This may be related to a bug with buildkit mentioned at the bottom of https://docs.docker.com/develop/develop-images/build_enhancements/. Can you please have a look?

Thanks @rafalzydowicz. Will take a look as soon as we get through the 0.8 release.

**Pull request merged**
