### PR TITLE
Updates to click==8.*

### PR DESCRIPTION
**Pull request by diogommartins**
**What this PR does / why we need it**:
Updates click from 7.x to 8.x - https://click.palletsprojects.com/en/8.0.x/upgrading/

```release-note
NONE
```

### CODE REVIEW

**Comment by adchia** [comment]
Thanks for the PR! Mind signing the commit to pass the DCO check?

**Comment by diogommartins** [comment]
> Thanks for the PR! Mind signing the commit to pass the DCO check?

Done it!

**Comment by adchia** [comment]
will also need to update the pip-tools requirements files: https://github.com/feast-dev/feast/tree/master/sdk/python/requirements

**Comment by diogommartins** [comment]
> will also need to update the pip-tools requirements files: https://github.com/feast-dev/feast/tree/master/sdk/python/requirements

will do

**Comment by woop** [comment]
Is there any reason to only support a single major version?

**Comment by diogommartins** [comment]
> Is there any reason to only support a single major version?

Since there isn't an interface change from 7.x and 8.x, I don't seed a reason not to support both. I fixed the version to 8.x to follow the previous design decision 🤷‍♂️

**Comment by adchia** [comment]
this seems fine to me. we can keep this unless someone else feels strongly.

/lgtm

**Review by adchia — APPROVED** [review]

**Pull request merged**
