### PR TITLE
Feature/v0.9/refresh auth0 token

### PR DESCRIPTION
**Pull request by AnujaVane**
**What this PR does / why we need it**: Refreshes the OAuth token 500 seconds before it expires

**Does this PR introduce a user-facing change?**: NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by AnujaVane** [comment]
Hey @woop like we discussed in the previously opened PR, I branched off of the v0.9 branch and made these changes. For some reason I see a CI build fail, it doesn't seem to be related to my changes though.

**Comment by woop** [comment]
@AnujaVane what happens when this token expires currently? I'm trying to figure out if pre-emptive refreshing is a good practice or not.

**Comment by AnujaVane** [comment]
@woop Currently, after expiration, it needs us to instantiate the Client again. Also I see a similar implementation is already in place for Google Auth.

**Review by woop — APPROVED** [review]

**Comment by AnujaVane** [comment]
Hey @woop just wondering when would a new tag/version be released for v0.9 along with this change?

**Comment by AnujaVane** [comment]
Hey @woop just following up my question incase you may have missed it. I looked through the docs as well but couldn't find a release schedule.

**Pull request merged**
