### PR TITLE
Enforce case-insensitively unique feature view names

### PR DESCRIPTION
**Pull request by codyjlin**
Signed-off-by: Cody Lin <codyl@twitter.com>

**What this PR does / why we need it**:
CockroachDB's table names and the materialization jobs using dataflow need feature view names to be lowercase. (CRDB is an online store we're trying to use.) We can transform the names downstream / on our end, but we would like the collision check to happen at `feast apply` time.

**Which issue(s) this PR fixes**:

It's such a small change that no issue created.

**Does this PR introduce a user-facing change?**:

```release-note
FeatureView names must now be *case-insensitively* unique
```

### CODE REVIEW

**Review by achals — APPROVED** [review]
I think this is fine, but is going to be a breaking change in case anyway was relying on this behavior. 

Any tests to update for this?

**Comment by codyjlin** [comment]
> Any tests to update for this?

@achals Ah, didn't realize there were tests for this validation check. Updating the failed tests and modifying one to test the case-insensitive case.

**Review by achals — APPROVED** [review]
/lgtm

**Pull request merged**
