### PR TITLE
duplicate columns from the offline redshift select sql query

### PR DESCRIPTION
**Pull request by gopalladha**
**What this PR does / why we need it**:
Calling https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/feature_store.py#L464 created the redshift query using https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/feature_store.py#L464. This redshift query is being generated as to `select *` at https://github.com/feast-dev/feast/blob/v0.13-branch/sdk/python/feast/infra/offline_stores/redshift.py#L520, which is causing duplicated columns (except entity columns, entity_timestamp & zipcode_features__entity_row_unique_id) being selected in the query.
Note: zipcode_features__entity_row_unique_id is taken as reference from https://github.com/feast-dev/real-time-credit-scoring-on-aws-tutorial

**Which issue(s) this PR fixes**:

Fixes 1917

**Does this PR introduce a user-facing change?**:

```Fixes the issue of duplicates columns for the get_historical_features data pull from offline redshift. Entity columns, entity_timestamp & zipcode_features__entity_row_unique_id are already not coming as duplicated, but rest all columns are getting duplicated in the result of the select query, which is being fixed by this release.
Note: zipcode_features__entity_row_unique_id is taken as reference from https://github.com/feast-dev/real-time-credit-scoring-on-aws-tutorial

```

### CODE REVIEW

**Comment by felixwang9817** [comment]
@gopalladha thanks for the PR! As noted [here](https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md), we expect all commits to signed. Would you mind signing your commit with `git commit -s`?

**Comment by gopalladha** [comment]
@felixwang9817 Thanks for the note and sorry I missed that earlier. I just did another small comments update commit with signed option. 
Ref: https://github.com/feast-dev/feast/pull/1922#issuecomment-933011233

**Comment by felixwang9817** [comment]
@gopalladha thanks. Can you check if #1911 solves your problem?

**Comment by gopalladha** [comment]
@felixwang9817 I was in discussion with @adchia in slack regarding [1911](https://github.com/feast-dev/feast/pull/1911) PR, and per his suggestion, I pulled master branch from https://github.com/feast-dev/feast to my local and using that installed feast with aws, and tried to run it, but I still got the same column duplicate error. So, it looks like master branch of https://github.com/feast-dev/feast  is still having this issue.
I provided updates to @adchia as well on the slack thread.

**Comment by MattDelac** [comment]
Otherwise https://github.com/feast-dev/feast/pull/1911 should fix this issue

**Comment by gopalladha** [comment]
@MattDelac I retried it with feast 0.15.0 version but I still get column ambiguous error. However that error goes away if I apply this PR changes in my local and try with that.

**Comment by MattDelac** [comment]
> @MattDelac I retried it with feast 0.15.0 version but I still get column ambiguous error. However that error goes away if I apply this PR changes in my local and try with that.

Weird because it looks like the change is part of 0.15.0 https://github.com/feast-dev/feast/blob/v0.15.0/sdk/python/feast/infra/offline_stores/bigquery.py#L574

Have you tried with 0.15.1 ?

**Comment by adchia** [comment]
@gopalladha what's the latest status on this? Are you still experiencing this?

**Comment by achals** [comment]
Hi @gopalladha, are you still planning on working on this PR? Is there anything we can do to help?

**Comment by adchia** [comment]
closing due to inactivity

**Pull request closed without merging**
