### PR TITLE
chore: Extend pandas version support

### PR DESCRIPTION
**Pull request by sudohainguyen**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by adchia — APPROVED** [review]
/lgtm

**Comment by sudohainguyen** [comment]
hi @adchia java integration test failed

**Comment by sudohainguyen** [comment]
just retriggered the pipelines, please approve again @adchia

**Comment by adchia** [comment]
Turns out this was a legitimate error (the tests also showed an issue with the pyarrow version used in the java tests). Fixed it + updated teh requirements.txt files too

**Comment by adchia** [comment]
Looks like there's some failing tests from the upgrade

**Comment by sudohainguyen** [comment]
https://stackoverflow.com/questions/76389694/transforming-pyspark-to-pandas-dataframe

looks like latest pyspark is not ready yet for pandas 2.0

**Pull request closed without merging**
