### PR TITLE
test: Fix a few integration tests for SparkOfflineStore plugin

### PR DESCRIPTION
**Pull request by jbvaningen**
…hift templates, this fixes some integration tests

Relates to https://github.com/feast-dev/feast/issues/2387

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by kevjumba** [comment]
@jbvaningen There are some lint errors that need addressing but overall looks good.

**Comment by kevjumba** [comment]
@jbvaningen Still some linting issues!

**Comment by jbvaningen** [comment]
Moved changes to new PR, https://github.com/feast-dev/feast/pull/2490 closing this one

**Pull request closed without merging**
