### PR TITLE
Split apply total parse repo

### LINKED ISSUE #2128: Split up parse_repo and apply_total
**Is your feature request related to a problem? Please describe.**
I have a framework that handles the offline store. It creates the tables, indexes, reads data from different data sources, does some transformations, and then inserts into the offline store. As a part of this, I can construct the entities, feature views, feature services, etc, a instance of the ParsedRepo class for Feast. What I need is the ability to pass my instance into the `apply_total` method.

**Describe the solution you'd like**
Remove the call to `parse_repo` from the `apply_total` ( [link](https://github.com/feast-dev/feast/blob/497809f216b7b8051ad6611df75795c25694e287/sdk/python/feast/repo_operations.py#L144) ) and instead perform that call elsewhere and pass the ParsedRepo object into the `apply_total` function.

**Describe alternatives you've considered**
Copy the `apply_total` method into my code and make the changes needed.
The reason why I don't like this approach is because I would be maintaining a copy/paste of the method, while the change in the Feast repo wouldn't impact functionality since `feast apply` would still call `parse_repo` and then pass the object to `apply_total`.

```python
@cli.command("apply", cls=NoOptionDefaultFormat)
@click.option(
    "--skip-source-validation",
    is_flag=True,
    help="Don't validate the data sources by checking for that the tables exist.",
)
@click.pass_context
def apply_total_command(ctx: click.Context, skip_source_validation: bool):
    """
    Create or update a feature store deployment
    """
    repo = ctx.obj["CHDIR"]
    cli_check_repo(repo)
    repo_config = load_repo_config(repo)
    try:
        parsed_repo = parse_repo(repo) # <- this
        apply_total(parsed_repo, repo_config, repo, skip_source_validation)
    except FeastProviderLoginError as e:
        print(str(e))
```

### PR DESCRIPTION
**Pull request by mickey-liu**
**What this PR does / why we need it**:
Need a way to pass a user-defined repo to the apply_total method. Added a new method which `apply_total` will now call that takes a RepoContents arg

**Which issue(s) this PR fixes**:
Fixes #2128

**Does this PR introduce a user-facing change?**:
```release-note
1. Added functionality
2. No User action required
3. added method: apply_total_with_repo_instance()
4. See #2128 
```

### CODE REVIEW

**Comment by felixwang9817** [comment]
hey @mickey-liu, this PR looks good to me! would you mind fixing the lint errors and pushing again? you can fix the lint errors with `make format-python` and `make lint-python` - see this [page](https://github.com/feast-dev/feast/blob/master/CONTRIBUTING.md) for more details

**Comment by mickey-liu** [comment]
@felixwang9817 thanks for the review. I just updated the PR with the lint fixes.

**Review by felixwang9817 — APPROVED** [review]
/lgtm

**Pull request merged**
