### PR TITLE
chore: Adjusting the file version validation for minor releases

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
# What this PR does / why we need it:

This is changing the validation to ignore patch version changes. So the CI should trigger correctly for increments from `0.37.1` -> `0.38.0`.

```bash
python infra/scripts/release/bump_file_versions.py 0.37.0 0.38.0
Updated 16 files with new version 0.38.0
```

Previously this failed as `0.37.1` wasn't recognized as a tag.

# Which issue(s) this PR fixes:

# Fixes

### CODE REVIEW

**Review by sudohainguyen — APPROVED** [review]
lgtm 😄

**Review by tokoko — COMMENTED** [review]
Despite validation, this is still not going to work, as line 48 looks for the passed `current_version` to replace in files. I think much easier solution is to simply revert version bumps.

**Comment by franciscojavierarceo** [comment]
> Despite validation, this is still not going to work, as line 48 looks for the passed `current_version` to replace in files. I think much easier solution is to simply revert version bumps.

The version bumps are automatically generated through this code. Are you suggesting we do that for every patch release @tokoko?

**Comment by tokoko** [comment]
@franciscojavierarceo No, version bumps to 0.37.1 was automatic, but not on master, it was done on `v-0.37-branch`. We manually introduced those version bumps to master with a later PR (#4127) which was a mistake. I don't mind if we scrap validation from the scripts either, just pointing out that it's unnecessary if we simply revert some of the changes from that PR (version bumps specifically).

**Comment by franciscojavierarceo** [comment]
> We manually introduced those version bumps to master with a later PR (#4127) which was a mistake. 

Got it! I missed this, my bad. Lack of sleep 🥲 .

**Comment by franciscojavierarceo** [comment]
@tokoko https://github.com/feast-dev/feast/pull/4227

**Pull request merged**
